pop-os/cosmic-comp

.gitignore
config.ron
debian/cosmic-comp.install

This makes sure config.ron is installed at /etc/cosmic-comp/config.ron in the debian packaging, and sets the default shortcuts to ones closer to those used on Pop. There are some TODOs in the updated config file to indicate what needs to be done to better match Pop's current shortcuts.

Install default config file, set Pop-like keyboard shortcuts

---

src/backend/kms/mod.rs

Fixes issue where default layout had displays positioned vertically
with gaps.

Don't mix up `x` and `y` arranging display outputs

---

config.ron
debian/control

For display brightness, this requires `cosmic-settings-daemon` to be running.

Add keybindings for volume, display brightness

---

src/config/mod.rs

Fixes https://github.com/pop-os/cosmic-comp/issues/29
While the setting was correctly read-out from the device, changes were not applied as the necessary code for this particular setting was just missing..
@jacobgkau Can you confirm this fixes your problem?

config: Set click_method for input devices

---

Cargo.lock
Cargo.toml
src/backend/kms/mod.rs
src/backend/render/mod.rs
src/backend/winit.rs
src/backend/x11.rs
src/config/mod.rs
src/config/types.rs
src/input/mod.rs
src/shell/grabs.rs
src/shell/layout/floating/mod.rs
src/shell/layout/mod.rs
src/shell/mod.rs
src/shell/workspace.rs
src/state.rs
src/utils/prelude.rs
src/wayland/handlers/export_dmabuf.rs
src/wayland/handlers/keyboard_shortcuts_inhibit.rs
src/wayland/handlers/layer_shell.rs
src/wayland/handlers/mod.rs
src/wayland/handlers/output_configuration.rs
src/wayland/handlers/xdg_shell/mod.rs
src/wayland/handlers/xdg_shell/popup.rs
src/wayland/protocols/output_configuration.rs
src/wayland/protocols/toplevel_info.rs
src/wayland/protocols/toplevel_management.rs
src/wayland/protocols/workspace.rs

We may want to restrict what applications can use this protocol in some way? I guess the ecosystem is still figuring out how to restrict which Wayland protocols sandboxed (Flatpak) apps can use. For now, always allow.

Update smithay and implement shortcuts inhibit protocol

---

src/shell/grabs.rs

Sometimes recently when I moved a window to a different workspace it would cause cosmic-comp to crash, and I noticed that it was because of the unwrap here. I've just made it return instead of unwrapping, which seems to have solved the issue, but maybe there is a better fix.

fix: return if output is none

---

src/wayland/handlers/screencopy.rs

This uses the same size that is later tested when capturing. So it doesn't error about a size mismatch.
Fixes https://github.com/pop-os/cosmic-comp/issues/52.

Fix advertised buffer size for shm toplevel capture

---

.github/workflows/build.yml
.gitignore
flake.lock
flake.nix

The `build` workflow currently just compile the `cosmic-comp` binary according to `flake.nix`.
Currently it is set to trigger when there are new commits on `master_jammy` or any pull requests targeting it.
A potential thing to do is to setup a Cachix cache (cachix.org), which will cut down CI time and allow Nix users to avoid building the project locally if they choose to use the cache.
I've setup a similar cache on my other project (https://github.com/cosette-solver/cosette-prover), but the setup requires creating an account on cachix.org and setting an API key in the repository secrets.
Usage of the Cachix service is free up to a certain quota, and if any maintainer is willing to do this, I can update the workflow file accordingly to make use of the cache.

Setup Github CI.

---

Cargo.lock
Cargo.toml
src/logger/mod.rs

This integrates a bit better than having `cosmic-session` copy logs from stderr to journald, and works when not started through `cosmic-session`.
Having panics logged should be helpful if panics ever occur.

Log to journald, and log panics

---

debian/control

The `control` file is invalid without the newline before `Package:`, and fails to build.
Generally, libraries shouldn't be listed under `Dependencies`. The -dev versions should be listed under `Build-Dependencies`, and `shlibs` automatically adds runtime dependencies based on the linked libraries with the version of the library that was linked.
`libsystemd` also doesn't exist, the package is `libsystemd0`. But is that actually needed? Looks like it's pulled in by `libseat1` and not used directly. `libxcb1` shouldn't be needed, x11rb provides a Rust implementation, and doesn't support integration with libxcb without the `allow-unsafe-code` feature, which doesn't seem to be used here.
For things that are opened with `dlopen`, this doesn't apply, though it would probably be best to avoid …

Fixes for debian packaging

---

src/backend/kms/mod.rs
src/backend/render/mod.rs
src/shell/workspace.rs
src/wayland/handlers/screencopy.rs

Not especially elegant, but simple enough. And works, mostly.
This doesn't capture correctly for the current workspace. I guess it's rendered only once, and the render for display on the screen has the layer shell surface? (There's a comment about this for cursors, which are also captured when they shouldn't be.)

Exclude "workspace-overview" from workspace screencopy

---

src/logger/mod.rs

I've also changed the log level from info to warn if there are no debug assertions for cosmic_comp & smithay. It seemed to have performance issues in electron apps for me otherwise.

fix(init_logger): Directive::from_str expects warn

---

Cargo.toml
src/main.rs

The `libsystemd` crate fails to build on FreeBSD and is presumably undesirable on any non-systemd distros. At least at present it's easy to make it optional.

Add default `systemd` feature flag to enable systemd integration

---

src/shell/layout/floating/grabs/moving.rs

This fixes two issues that seem to have been introduced by 98dc342:
* During drag, CSD windows being offset from their original location and the frames rendered around them.
* Windows on additional monitors being positioned incorrectly when dragged.
This seems to work well in floating mode with `OutputBound` workspaces. With `Global` workspaces it seems position of dragged windows on additional monitors isn't right before or after this...

shell: Fix position of floating windows before/after drag

---

src/backend/render/mod.rs
src/shell/layout/floating/mod.rs
src/shell/workspace.rs

* Render window and active indicator at correct position relative to where the output is within the space.
* Show active indicator around whole window, not only part of window on focused output.

Fixes for rendering windows in `Global` workspace mode

---

Makefile
debian/rules
debian/source/options
src/input/mod.rs

Each invocation of `Action::Spawn` was spawning a process without waiting on the child; resulting in an accumulation of zombie sh processes. This will spawn them in a background thread which waits on the child so that it can be reaped.

fix zombie processes from Action::Spawn

---

.github/workflows/build.yml
flake.lock
flake.nix

Fix the build issues and update dependencies.
Currently I can successfully build the binary on my laptop, but when running it, I encountered the following error.
<details>
```
2023-06-02T04:28:33.407325Z  WARN cosmic_comp::config::types: Key-Binding 'Period' only matched case insensitive for "period"
2023-06-02T04:28:33.407404Z  WARN cosmic_comp::config::types: Key-Binding 'Comma' only matched case insensitive for "comma"
2023-06-02T04:28:33.407422Z  WARN cosmic_comp::config::types: Key-Binding 'Period' only matched case insensitive for "period"
2023-06-02T04:28:33.407434Z  WARN cosmic_comp::config::types: Key-Binding 'Comma' only matched case insensitive for "comma"
2023-06-02T04:28:33.471306Z  WARN cosmic_comp::backend::x11: Failed to instanciate vulkan, falling back to gbm allocator. …
```

Update Nix flake and CI.

---

src/shell/element/mod.rs
src/shell/element/surface.rs
src/shell/element/window.rs
src/shell/layout/floating/grabs/resize.rs
src/shell/layout/floating/mod.rs
src/shell/layout/tiling/mod.rs
src/shell/workspace.rs
src/wayland/handlers/toplevel_info.rs

Superseeds #131, should fix #125.
Fixes the intent of the `is_maximized || is_fullscreen`-checks of the tiling layer, causing the geometry to be correctly restored by `recalculate`.

shell: Allow querying current vs pending state

---

src/config/mod.rs
src/config/types.rs

I noticed https://github.com/pop-os/cosmic-comp/issues/17 again, but this time I realized num lock was on. Hopefully this is the only cause of that issue (and caps lock, but that is easier to notice).
I don't think we would event want either of these states to be part of a key binding. And `KeyModifiers` doesn't seem to be used anywhere else this would be relevant. So they can be ignored. This should be more similar to how keybindings are handled elsewhere.

Ignore caps/num lock in key bindings

---

src/shell/workspace.rs

`or.geometry()` was actually calling a different method in `filter` than in `.flat_map`. Apparently since `or` in `filter` is an `&&X11Surface` instead of `&X11Surface`, that invoked the trait method on `SpaceElement`...
Smithay should be changed in some way so that can't happen, but this improves some of the behavior in cosmic-comp for now, at least. There may be other issues related to this.
The `SpaceElement::geometry` was also returning a `loc` of `(0, 0)`, which presumably isn't correct either.

Fix output filtering of override-redirect windows

---

Cargo.lock
Cargo.toml
src/shell/workspace.rs

We shouldn't be sending configures to override-redirect surfaces.
Requires https://github.com/Smithay/smithay/pull/1094 to behave correctly.

xwm: Don't pass override-redirect surfaces to `update_stacking_order*`

---

src/shell/workspace.rs

This was setting the wrong order, and thus also fighting with `raise_window`, creating a flood of configure events. Which seemed to break submenus in Gimp when multiple toplevels were open.
This appears to be correct.

xwm: Don't pass reverse order to `update_stacking_order_upwards`

---

cosmic-comp-config/src/input.rs
src/config/input_config.rs
src/config/mod.rs
src/input/mod.rs

This is not a setting handled by libinput; we have to scale the scrolling ourselves.
This should match the behavior of the `scroll_factor` defined in sway-input(5).

input: Add a `scroll_factor` config option

---

Cargo.lock
Cargo.toml
src/input/mod.rs

The protocol doesn't specify this, but XWayland does assume relative pointer events are part of a frame.
This works for now, though a better solution will be needed in Smithay to also handle pointer constraints where a relative motion may occur alone, etc.
This seems to fix https://github.com/pop-os/cosmic-comp/issues/159.

Send `relative_pointer` in frame with `pointer`; update Smithay

---

src/shell/layout/tiling/mod.rs

I didn't see any issue with how mouse events were handled, but a bisect showed b818a68a91c83cd3ab5da79cebb5f144cb2feeee caused the issue. Reverting the definition of `element_under` to the version before that change fixed the behavior.
Comparing what both versions return, the right element is returned, but the location returned is wrong. This makes the return value match the position that was returned by the previous implementation. It seems to be working correctly now.
Fixes https://github.com/pop-os/cosmic-comp/issues/161.

Fix `TilingLayout::element_under` position with global workspaces

---

src/wayland/handlers/compositor.rs

Consider a simple client that doesn't use `set_window_geometry`, committing after attaching a buffer to a window surface.
`Window::geometry` falls back to `Window::bbox`, but when `Shell::map_window` called `Window::geometry`, `Window::bbox` hadn't been set yet, because that only happened later in `<State as CompositorHandler>::commit`, so the window would be mapped with a size of (0, 0).
This resulted in server-side decorations not being drawn for such clients until they were re-focused or resized.
The fix is to add an extra call to `Window::on_commit` before mapping it, so that its bbox is set correctly when `Shell::map_window` asks for its geometry.

wayland: map windows with correct geometry

---

src/input/mod.rs

This fixes #160, but I am not sure when Shell::activate is supposed to return a position versus when it is not.

Fix NextOutput and PreviousOutput when Shell::activate returns None

---

Cargo.lock
Cargo.toml
src/input/mod.rs
src/shell/element/mod.rs
src/shell/element/stack.rs
src/shell/element/surface.rs
src/shell/element/window.rs
src/shell/focus/target.rs
src/shell/grabs/mod.rs
src/shell/grabs/moving.rs
src/shell/layout/floating/grabs/resize.rs
src/shell/layout/tiling/grabs/resize.rs
src/state.rs
src/utils/iced.rs
src/wayland/handlers/mod.rs
src/wayland/handlers/pointer_constraints.rs

Depends on https://github.com/Smithay/smithay/pull/872.
For some reason, pointer confinement isn't working correctly here at the moment, even though the code matches Anvil...
May need solution to https://github.com/Smithay/smithay/issues/1126 for behavior to be correct.

Pointer constraints

---

config.ron

I guess we need another method for the default terminal. Maybe something like `i3-reasonable-terminal` or `x-terminal-emulator`.

use xdg-open for default browser and file explorer in config.ron

---

Cargo.lock
Cargo.toml
src/backend/render/cursor.rs
src/input/mod.rs
src/state.rs
src/utils/prelude.rs
src/wayland/handlers/data_device.rs
src/wayland/handlers/mod.rs
src/wayland/handlers/primary_selection.rs
src/wayland/handlers/seat.rs
src/wayland/handlers/selection.rs
src/xwayland.rs

We'll probably want to add support for `cursor-shape-v1`. Not sure about `wlr-data-control-unstable-v1`. But this just updates to work with the latest smithay commit for new.

Update `smithay`, with cursor/selection changes

---

config.ron
cosmic-comp-config/src/lib.rs
cosmic-comp-config/src/workspace.rs
src/backend/render/mod.rs
src/config/key_bindings.rs
src/config/mod.rs
src/input/mod.rs
src/shell/mod.rs
src/wayland/protocols/workspace.rs

`WorkspaceAmount` now can be changed dynamically, which seems to basically work. We'll see how that works with `WorkspaceMode` and `WorkspaceLayout`.
If `WorkspaceLayout` can be changed at runtime, we'll have to update default keybindings in some way.

Use cosmic-config for workspace settings

---

src/shell/focus/mod.rs

This should now match the protocol specification, and how Sway behaves.
If a surface in the `Top` or `Overlay` has `KeyboardInteractivity::Exclusive`, only that surface can have keyboard focus. If multiple surfaces do, focus can be changed between those with keyboard exclusivity on the highest layer.
This is similar to session lock surfaces, except a session lock takes precedence.
This fixes the behavior of keyboard focus in `cosmic-greeter`, with the current layer-shell based implementation.

Fix handling of layer shell surface with exclusive interactivity

---

Cargo.lock
Cargo.toml
src/shell/mod.rs
src/state.rs
src/wayland/handlers/security_context.rs

Draft until everything is updated to not break. Perhaps this should be split in two commits. One that enables security-contexts to inherit the privileged flag and one that enables all the enforcing, that can be merged later.
In any case this breaks parts of the desktop today, but once cosmic-panel makes use of security-context applets could even enjoy more privileges. E.g. always creating valid xdg-activiation tokens via #207.

wayland: Privileged protocol security

---

src/state.rs
src/wayland/handlers/session_lock.rs

This makes it possible to handle a crash in the session lock client by restarting it, for instance. This is similar to how Sway behaves.
Depends on Smithay change.

Allow session lock if existing session lock is no longer valid

---

src/state.rs

Otherwise we gain absolutely nothing by inheriting the privileged flag. :see_no_evil:
There is also the question, if we should allow privileged clients with a context to access the security-context protocol itself, but that is a far less important question.

state: fix privileged access with sec context

---

Cargo.lock
Cargo.toml
src/input/mod.rs
src/shell/focus/mod.rs
src/shell/layout/floating/mod.rs
src/shell/mod.rs
src/shell/workspace.rs
src/utils/iced.rs
src/wayland/handlers/mod.rs
src/wayland/handlers/screencopy.rs
src/wayland/handlers/xdg_activation.rs
src/wayland/handlers/xdg_shell/mod.rs
src/xwayland.rs

This provides an initial implementation of the xdg-activation protocol to prevent focus stealing, passing of focus by client (e.g. required to fix #192) voluntarily, additional context for new apps (e.g. workspace they were launched from) and urgent state for workspaces.
Draft until this is used by cosmic-launcher/cosmic-applibrary.

xdg-activation: Initial implementation

---

src/backend/render/mod.rs
src/input/mod.rs
src/shell/focus/mod.rs
src/shell/mod.rs
src/state.rs
src/wayland/handlers/session_lock.rs

Fixes issue with re-draw not being queued on initial surface commit until cursor is moved.

Handle session lock surfaces in `visible_outputs_for_surface`

---

config.ron
src/config/key_bindings.rs
src/input/mod.rs
src/shell/mod.rs

This adds the necessary actions that take direction into account when moving focus and windows between outputs. It also makes the workspace shortcuts fail over to the corresponding output shortcuts and the focus/move shortcuts handle outputs first, before considering workspaces.
Overall this should make the movement options finally be consistent with the output arrangement set in `outputs.ron` or via `wlr-output-configuration`, instead of using meaningless array indices.

Output arrangement

---

config.ron

Should be merged with https://github.com/pop-os/cosmic-workspaces-epoch/pull/8, https://github.com/pop-os/cosmic-applibrary/pull/65, and https://github.com/pop-os/cosmic-launcher/pull/72

chore: update the config to spawn launcher, app-library, and workspaces when shortcuts are pressed

---

Cargo.lock
src/shell/grabs/menu/default.rs
src/shell/mod.rs
src/wayland/handlers/toplevel_management.rs
src/wayland/protocols/toplevel_management.rs
src/wayland/protocols/workspace.rs

Needed for `cosmic-workspaces`.
Requires https://github.com/pop-os/cosmic-protocols/pull/21. This dependency will need to be updated here when that is merged.

workspace-management: Implement `move_to_workspace` requested

---

src/wayland/handlers/dmabuf.rs

Somehow when updating to this API, I missed the call to `successful`.
This doesn't seem to make a difference for most clients since `create_immed` is normally used. But should correct anything using `create`.

Fix use of `ImportNotifier`

---

Cargo.lock
cosmic-comp-config/Cargo.toml
cosmic-comp-config/src/input.rs
cosmic-comp-config/src/lib.rs
cosmic-comp-config/src/workspace.rs
src/config/mod.rs

It seems to derive `CosmicConfigEntry`, we need to use `_` in property names, because `_` isn't mapped to `-` and there doesn't seem to be a mechanism like `#[serde(rename)]`.
It seems good to be consistent anyway. So this seems good to change, unless we really like using `-` for names on disk, then cosmic-panel needs to be changed.
`CosmicConfigEntry` also requires `PartialEq`, which is easy enough to add.
This will break existing input settings, which will have to be re-applied with the new locations. Cosmic-settings also need to be updated for this.

cosmic: Provide `CosmicConfigEntry` impl, use `_` in property names

---

Cargo.lock
Cargo.toml
src/input/mod.rs

`axis_stop` should only be sent if the value is `Some(0)`, while this also sent it for `None`. So every scroll event on one axis generated stop events for the other.
This fixes scrolling with a touchpad in Alacritty.
Anvil already does this, comparing against `Some(0.0)`.

Fix generation of `axis_stop` events 

---

cosmic-comp-config/src/input.rs
src/config/input_config.rs
src/config/mod.rs
src/input/mod.rs
src/shell/mod.rs

A very rough implementation, that is sufficient to get a touchscreen device working.
I'm not sure how we should detect which output is associated with a touchscreen device.
The Smithay APIs for touch events could probably be improved a bit.

Initial `wl_touch` support

---

config.ron

On Pop!_OS, Super+Escape locks the screen: https://support.system76.com/articles/pop-keyboard-shortcuts/
The PR moves the `Debug` action over to Super+Ctrl+Escape, and then wires up `cosmic-greeter` so that we get the same lock screen keyboard shortcut here

fix: Super+Escape locks screen per Pop!_OS convention

---

src/config/mod.rs

It seems these two lines were omitted in https://github.com/pop-os/cosmic-comp/pull/254, so it was reading the "xkb_config" settings at startup, then watching "xkb-config".
The other settings seem to be consistent.
This should fix https://github.com/pop-os/cosmic-comp/issues/285 (though it will also be necessary to edit "xkb_config", rather than the old file.

Change "xkb-config" to "xkb_config" in remaining place

---

src/input/mod.rs

This matches Sway, and seems to make it harder to accidentally paste text twice.
Perhaps this should be configurable in some way (not sure how it's usually handled). But this is probably a better default.

Change keyboard repeat delay from 200ms to 600ms

---

src/shell/grabs/moving.rs
src/shell/layout/floating/mod.rs
src/shell/mod.rs
src/shell/workspace.rs

And a bunch of fixes for geometry restoring in floating mode.

floating: Maximize animation

---

Cargo.lock
Cargo.toml
cosmic-comp-config/Cargo.toml
src/backend/kms/mod.rs
src/backend/x11.rs
src/input/mod.rs
src/wayland/handlers/output.rs

Pretty basic update.
- Doesn't handle the new X11 focus event in any way
- Doesn't handle new switch events, to e.g. handle lid-close
- Doesn't use the new OutputHandler to fix various deficiencies in our cosmic-toplevel/workspace protocols regarding later bound outputs.

chore: Update smithay

---

src/shell/mod.rs

this ensures new workspaces are correctly set to autotile or float

fix: set autotile for al workspace sets when there is a change

---

src/backend/render/cursor.rs
src/wayland/handlers/screencopy.rs

smithay only considers memory based cursor elements for scan-out on a cursor plane.
without this change the default system cursor won't be put on a cursor plane.

use memory for system cursor

---

src/shell/element/stack.rs
src/shell/element/stack/tab.rs
src/shell/element/stack/tab_text.rs
src/shell/element/stack/tabs.rs

Updates colors for the stack tabs to match the current values from the design documentation.
This will noticeably improve visibility of tabs when using a light theme.

fix(stack): set correct colors for light theme

---

src/input/mod.rs
src/wayland/handlers/seat.rs

It doesn't seem there's currently a way to iterate over input devices, so this adds a `Vec` of libinput keyboard devices. When run with the kms backend.
Not the most elegant solution, but it doesn't seem practical to add a type generic to `Devices` given how backends are handled, and `Device` can't be made into a trait object. Another trait could be added, but this is fine, and technically should perform better (but if it actually had to iterate over many keyboards, something has gone very wrong).

Set keyboard LEDs (capslock, numlock, scrollock)

---

src/config/mod.rs

I was testing cosmic DE and while configuring the keymaps I accidentally broke the keymap config file.
This makes cosmic-comp to crash and you must go through another desktop environment to change the config and fix it.
I think it's better to log the error and skip the file.
Also I was having a specific issue when installing from cosmic-epoch, they are no keymaps by default when no config is found. The second commit adds the default `config.ron` keymaps if no config file is found. It is a specific issue so I don't know if you want that.
Thanks for all of your amazing work, can't wait to see the alpha.
Also love the blog posts, they are really well made.

fix: Avoid crash on malformed keymap config

---

src/backend/render/mod.rs
src/shell/grabs/moving.rs
src/shell/layout/floating/mod.rs

this pr enables dragging the mouse to the output edges to maximize, or half tile in any direction
* ~~right now only maximize works, can't figure out why the half tiling isn't working~~ **fixed**
* ~~currently rendering an outline, not a shaded region, I'm looking for how to render a shaded region instead~~
* ~~the shaded region covers the whole output, not just the area between panels~~ **fixed**
* ~the drag regions don't extend into the panels, making it kind of awkward to maximize when there is a top panel for example~ **fixed**
https://github.com/pop-os/cosmic-comp/assets/56272643/32f0d6a0-c164-4f3b-91af-60db6c0b43aa

feat: drag regions for maximize and half tiling

---

Cargo.lock
Cargo.toml
src/backend/kms/mod.rs
src/backend/render/cursor.rs
src/backend/render/mod.rs
src/backend/winit.rs
src/main.rs
src/shell/element/mod.rs
src/shell/element/surface.rs
src/shell/element/window.rs
src/shell/grabs/moving.rs
src/shell/layout/floating/mod.rs
src/shell/layout/tiling/mod.rs
src/shell/mod.rs
src/shell/workspace.rs
src/state.rs
src/utils/iced.rs
src/wayland/handlers/screencopy.rs

I'm not sure entirely how to deal with `profiling::finish_frame!` when there are multiple outputs rendering frames, and some more functions could be annotated, but Tracy seems generally useful for profiling with these changes. So they might as well be merged.

Add support for profiling using tracy

---

src/backend/render/animations/mod.rs
src/backend/render/animations/spring.rs
src/backend/render/mod.rs
src/input/gestures/mod.rs
src/input/mod.rs
src/shell/mod.rs
src/state.rs
src/wayland/handlers/toplevel_management.rs
src/wayland/handlers/workspace.rs

This PR implements the next workspace and previous workspace touchpad gestures.
To-do:
Left for a future PR:
Implementation details (OUTDATED):
* A new enum WorkspaceDelta is created (name can be changed) that can have either an Instant (with optional offset) or a delta from 0.0 to 1.0.
* A new tuple is added to State::Common called gesture_state which contains the number of fingers used, the total delta, and the direction the gesture is in.
* New constants GESTURE_MAX_LENGTH and GESTURE_THRESHOLD
* GESTURE_MAX_LENGTH is the maximum length of the gesture that moves the screen
* GESTURE_THRESHOLD is the percentage of the maximum length required to complete the workspace switch
* New functions in Shell that help update deltas for workspaces

feat: workspace switching touchpad gestures

---

config.ron

This adds the XF86AudioMicMute keyboard event to config.ron, pretty simple.

Add the XF86AudioMicMute keyboard event to config.ron

---

src/shell/workspace.rs

Using `is_tiled()` here doesn't work for fullscreen windows, since `is_tiled()` returns `false` for them.
This (plus the previous changes for supporting minimize) seems to fix the behavior of `SDL_MINIMIZE_ON_FOCUS_LOSS` in XWayland applications (https://github.com/pop-os/cosmic-comp/issues/231). Wine had a similar issue, though I haven't tested it yet.
It doesn't seem ideal visually that the fullscreen window becomes tiled then minimized itself, but that's less of a problem.
May need to check if this is an issue with any other uses of `is_tiled()` or `is_floating()`.

Fix `Workspace::minimize` for tiled fullscreen applications

---

Cargo.lock
Cargo.toml
src/input/mod.rs
src/shell/element/mod.rs
src/shell/element/stack.rs
src/shell/element/surface.rs
src/shell/element/window.rs
src/shell/focus/mod.rs
src/shell/focus/target.rs
src/shell/grabs/moving.rs
src/shell/layout/floating/mod.rs
src/shell/layout/tiling/mod.rs
src/shell/mod.rs
src/shell/workspace.rs
src/wayland/handlers/compositor.rs
src/wayland/handlers/seat.rs
src/wayland/handlers/xdg_shell/popup.rs

Continuation of https://github.com/pop-os/cosmic-comp/pull/322 to eventually bump smithay again.
This takes about half of @ids1024 original approach, by leaving the `KeyboardFocusTarget` as is and adjusting the `PointerFocusTarget` to go all the way and split up `CosmicMapped` focus into iced-UI and surfaces.
Reasoning:
- The smithay changes actually don't require us to adjust the keyboard focus and I don't think consolidating into a single `WlSurface` variant is a good idea, as we are loosing context. The old PR spent quite a bit of code to reconstruct toplevel-surfaces. Let's simply not do that.
- The new pointer focus logic is meant to fix inconsistencies when wrapping multiple elements, regarding grabs, which suddently can't differentiate anymore between the individual elements (which …

input: Rework PointerFocus to operate directly on WlSurface

---

src/shell/grabs/moving.rs

Without this check, a floating window that is dragged near an edge between monitors causes snapping indicators to show on both, since the window intersects both.

moving: Show `snapping_indicator` only on current output

---

src/shell/grabs/moving.rs

Reduces top snap range to 38, from 56, reducing top size to approximately 67.8% of the old size.
cc: @WatchMkr
fixes: https://github.com/pop-os/cosmic-comp/issues/408
I haven't tested this for usability yet, but it should be about 67.8% as usable /s
We could alternatively make the total size 32, like the other sides

fix: reduce size of top snap range

---

Cargo.lock
Cargo.toml
src/shell/grabs/menu/mod.rs
src/shell/grabs/mod.rs
src/shell/grabs/moving.rs
src/shell/layout/floating/grabs/resize.rs
src/shell/layout/tiling/grabs/resize.rs
src/shell/layout/tiling/grabs/swap.rs

Requires https://github.com/Smithay/smithay/pull/1386. Based on https://github.com/pop-os/cosmic-comp/pull/404, since that adds/changes grabs.
Fixes https://github.com/pop-os/cosmic-comp/issues/403.

Add `unset` method to grab traits

---

Cargo.lock
Cargo.toml
debian/control
src/backend/render/element.rs

I've been wondering for a why cosmic-comp wasn't using cursor planes, despite seemingly having doing everything needed to support them.
It seems there was just a missing implementation of the `kind()` method.

Fix support for cursor planes

---

src/shell/element/stack.rs
src/shell/element/window.rs

We already direct touch events to Iced, and the Cosmic `HeaderBar` widget already recognizes drags from touch events. So it seems updating `last_seat` is all that was needed for windows SSDs.
For stacks, the same works, plus moving using the same logic for detecting drags that is used for mouse events.

Support touch drag for SSD toplevels, and stacks

---

src/shell/grabs/moving.rs
src/shell/layout/floating/mod.rs

> **Note:** the images here are slightly old, the maximize state no longer has gaps, as @git-f0x pointed out that the maximized state in tiling mode doesn't have gaps
https://github.com/pop-os/cosmic-comp/assets/56272643/044df604-215c-4f2e-a222-946ae47ffd23
**Friendly reminder** tiling gaps can be configured in cosmic settings > appearance !

feat: floating window tiling gaps

---

Cargo.lock
src/backend/kms/mod.rs
src/backend/render/element.rs
src/config/mod.rs
src/state.rs
src/utils/prelude.rs
src/wayland/handlers/output_configuration.rs
src/wayland/protocols/output_configuration.rs
src/wayland/protocols/output_configuration/handlers/cosmic.rs
src/wayland/protocols/output_configuration/handlers/mod.rs
src/wayland/protocols/output_configuration/handlers/wlr.rs
src/wayland/protocols/output_configuration/mod.rs

Output mirroring! Including cases of mismatched resolutions/orientations/refresh-rates/gpus
TODO:

kms: Output mirroring

---

src/backend/kms/socket.rs
src/main.rs
src/session.rs
src/state.rs

Manually starting `cosmic-panel` was not working properly in release builds, because without `cfg!(debug_assertions)`, the `privileged` flag wasn't sent on the panel, so it couldn't be propagated to the applets, which also fail the `client_has_no_security_context()` check.
I don't see a way to have both the `cfg!(debug_assertions)` check and `COSMIC_ENABLE_WAYLAND_SECURITY`. Now only the latter is used, and it determines the value of `privileged` for clients started normally. In the future, we could make the default value of
`COSMIC_ENABLE_WAYLAND_SECURITY` depend on `cfg!(debug_assertions)` if desired. But it shouldn't be necessary to have `debug_assertions` to test clients, since that should work with normal release builds.
This also corrects the inconsistency that the …

Change how `COSMIC_ENABLE_WAYLAND_SECURITY`/`privileged` is handled

---

src/input/mod.rs

I wasn't sure if, or how, scaling should apply to the `scroll_value120` events. But it seems both sway and kwin just multiply by the scale factor then round, so that seems reasonable.
This seems to fix https://github.com/pop-os/cosmic-settings/issues/270.

fix: Apply `scroll_factor` to v120 events

---

Cargo.lock
Cargo.toml
src/backend/kms/socket.rs
src/backend/winit.rs
src/backend/x11.rs
src/state.rs

It seems this was needed for `renderer.bind_wl_display`. But only in the X11 and winit backends. Unless there's some less obvious reason to use the `use_system_lib` feature, it seems undesirable and avoidable.
This uses `WlDrmState` to provide `wl_drm` on those backends instead.
If I hide the dmabuf global, Mesa EGL clients seem to work fine using `wl_drm` here with both the winit and x11 backends.

Disable Smithay `use_system_lib` to use Rust backend to wayland-rs

---

Cargo.lock
Cargo.toml

The only thing added to Smithay since the last update is https://github.com/Smithay/smithay/pull/1437.
Fixes https://github.com/pop-os/cosmic-comp/issues/497.

Update Smithay with Nvidia `IN_FENCE_FD` fix

---

src/shell/element/surface.rs
src/xwayland.rs

This seems to fix the issue described in https://github.com/pop-os/cosmic-comp/issues/502 with XWayland dialogs not being allocated enough height.
This may also fix https://github.com/pop-os/cosmic-comp/issues/468, or that could be a similar issue. That will need more testing. If comic-comp gets the `geometry` of a window then calls `set_geometry`, if everything isn't perfectly symmetric that may lead to the sizing shrinking or growing like that.

Fixes for handling of SSDs in window geometry

---

Cargo.lock
Cargo.toml
src/input/mod.rs
src/shell/element/surface.rs
src/shell/element/window.rs

This PR sets the density of server side decorated headers to `Density::Compact`
Fixes: https://github.com/pop-os/cosmic-comp/issues/502 (the remaining part of it)
Before:
After:

design: Use compact headerbar for server-side-decorations

---

Cargo.lock
Cargo.toml
src/shell/element/mod.rs
src/shell/focus/mod.rs
src/wayland/handlers/seat.rs

This should fix https://github.com/pop-os/cosmic-comp/issues/494, and make clipboard and primary focus consistently correct.
Changing the active element of a stack needs to change the clipboard focus, but it wasn't being changed since the `KeyboardFocusTarget` was unchanged. The `CosmicStack` methods that change the active stack element also have no obvious way to change the keyboard focus. So we can set this in `refresh_focus`, which should be correct.
If the new focus `WlSurface` is `None`, this clears the focus instead of leaving it as the previous code did. I believe that is desirable.
Requires https://github.com/Smithay/smithay/pull/1442 to avoid repeated `offer`s, instead of only when focus changed.
(Perhaps this could better be solved by having a `WlSurface` variant of …

Set clipboard/primary focus in `refresh_focus`

---

src/backend/kms/device.rs
src/backend/kms/mod.rs
src/config/mod.rs
src/state.rs
src/wayland/handlers/output_configuration.rs

Should at least partially fix https://github.com/pop-os/cosmic-comp/issues/397.
Fixes the exact symptoms observed in:
- https://github.com/pop-os/cosmic-epoch/issues/394
- https://github.com/pop-os/cosmic-epoch/issues/391
Will reset output configuration for already bad settings (where parsing now with u32 will fail), but should simply correct any new bad configs, by offsetting everything.

output: Store position as u32 and offset bad configs

---

Cargo.lock
Cargo.toml
src/wayland/handlers/screencopy/render.rs

Fixes https://github.com/pop-os/cosmic-comp/issues/48.
https://github.com/Smithay/smithay/pull/1475 fixes the segfault so this instead produces an error. Then we need to handle the error here.

screencopy: Handle error from with_buffer_contents_mut 

---

Cargo.lock
Cargo.toml
src/input/mod.rs
src/shell/element/surface.rs
src/shell/focus/mod.rs
src/shell/focus/target.rs
src/shell/mod.rs
src/shell/workspace.rs
src/xwayland.rs

This seems to fix the majority of minimize-bugs happening with a lot of games. (Where maximizing the window immediately minimizes it again.)
The culprit was the `wl_keyboard::leave` event, causing the app to register a focus loss, when we switched between `KeyboardTarget::Element` and `KeyboardTarget::Fullscreen`. (Confusingly most games seem to unfullscreen themselves before minimizing and restore fullscreen state after unminimizing... causing this weird transition in our code.)
This skips the set of events (thanks to https://github.com/Smithay/smithay/pull/1479), when the new target represents the same surface, which should be fine?!
Dunno, this probably needs some more testing to see, if it doesn't break other apps, but first tests seem promising.
Ref:
- …

Fix xwm games

---

src/backend/kms/surface/mod.rs
src/backend/render/mod.rs
src/input/mod.rs
src/shell/element/mod.rs
src/shell/element/stack.rs
src/shell/element/surface.rs
src/shell/element/window.rs
src/shell/grabs/moving.rs
src/shell/layout/floating/mod.rs
src/shell/layout/tiling/mod.rs
src/shell/mod.rs
src/shell/workspace.rs
src/utils/mod.rs
src/utils/quirks.rs
src/wayland/handlers/screencopy/mod.rs
src/wayland/handlers/screencopy/render.rs

This helps with issues like https://github.com/pop-os/cosmic-workspaces-epoch/issues/59.
I'm not entirely happy with the growing complexity of `workspace_elements`. I was thinking of a couple ways to split it up, noticed the most redundant part was the repeated code extending `p_elements` and `w_elements`. And the cleanest way to de-duplicate that out is with a dedicated `SplitRenderElements` type, which could be good in general. I have a commit adding that.
This also adds the commit from https://github.com/pop-os/cosmic-comp/pull/459, which makes more of a difference now. (If we wanted an animation between workspaces with this, we'd need to make sure `cosmic-comp` and `cosmic-comp` animate in sync.)
This seems to generally work with cosmic-workspaces modified to leave the background …

Render only layer shell surfaces when `cosmic-workspaces` is open, and add a `SplitRenderElements`

---

src/input/mod.rs

Actions which are on release don't have anything to suppress, and end up suppressing the next release. fixes #640 . I'm not the most familiar with the input code, but I don't think that this fix should break anything.

fix: only suppress keys when an action is on press

---

src/input/mod.rs

I feel like this is the better approach rather then pretending the modifier event never happened. Potentially fixes missed inputs and cleans up this method a bit.

input: Send modifiers of modifier-only bindings to clients

---

cosmic-comp-config/src/lib.rs

Closes https://github.com/pop-os/iso/issues/332

chore(config): enable tap-to-click and disable-while-typing by default for touchpads

---

src/wayland/protocols/toplevel_info.rs

This fixes an issue with `cosmic-panel` where, when a workspace is moved back to an output after a monitor is disconnected and reconnected, the panel doesn't hide because `cosmic-panel` thinks no toplevel is open on that monitor.
After some testing, it seems `output_enter` isn't being sent here. In particular, the `output_leave` call happens before the client binds the `wl_output`, so there is no `wl_output` to send in an event yet.
This is addressed by keeping track of a set of `wl_output`s that we have sent the event to. So if an output is bound, `refresh` can add it to this list and send the event.
This is not needed for workspaces (though it could be done similarly) since the handle objects are created by server events. So no race should occur as long as the workspaces global is bound …

toplevel-info: Fix race between binding `wl_ouput` and `output_enter`

---

src/input/mod.rs

Relevant issue: #429 
This PR adds the ability to resize windows with super + right-click, based on the quadrant that the mouse is in at the time of the initial click.
This modifies the behaviour of the super + click to move window feature to only work with left clicks, as that previously worked with any sort of click, including middle or right clicks (which is probably not the intended behaviour).

Resize window with Super + Right-Click Drag

---

src/backend/render/element.rs
src/shell/element/mod.rs
src/shell/workspace.rs

It would make sense to have a bound like `for<'frame> R::Frame<'frame>: AsGlowFrame<'frame>`. But that appears to not behave properly due to current limitations of the borrow checker: https://blog.rust-lang.org/2022/10/28/gats-stabilization.html#implied-static-requirement-from-higher-ranked-trait-bounds
Instead, this makes `glow_frame` and `glow_frame_mut` associated functions of the `AsGlowRenderer` trait. Then it is pretty straightforward to make the `RenderElement` implementations generic using that and `FromGlesError`.
It would make sense to make `Self::Error: FromGlessError` a requirement of the `AsGlowRenderer` trait, but due to the lack of implied bounds support, that produces a bunch of errors about missing bounds. If Rustc improves that eventually, some bounds could be cleaned up …

Make `RenderElement` implementations generic to reduce duplication

---

src/backend/kms/mod.rs
src/backend/render/mod.rs
src/state.rs
src/utils/screenshot.rs
src/wayland/handlers/screencopy/mod.rs
src/wayland/handlers/screencopy/render.rs

The first commit abstracts things a bit to reduce duplication, with a slight negative diff. So we can add this variant to the kms backend without complicating things much.
This should help for testing in VMs without hardware acceleration, until pixman is fully integrated. `cosmic-workspaces` and `xdg-desktop-portal-cosmic` will need to be updated to not require the dmabuf global.
There are still some cases where panics can occur, but those should be a subset of existing panics. With pixman we should always have a working renderer.

Use `EGL_MESA_device_software` as fallback for screen capture

---

src/shell/layout/mod.rs

This prevents the flickering of windows when using wl-clipboard in certain editors (Helix, neovim)
Fixes #700

Add wl-clipboard to tiling exceptions

---

src/backend/kms/device.rs

This re-applies automatic dpi scaling, which was reverted on `master` for it's overly "aggressive" scaling.
Fractional scaling can still have it's issues (at least while our Xwayland scaling story isn't fully fleshed out) and several panels of our machines, that were specifically chosen for being usable at 100% scaling with their native resolution now defaulted to 125%.
To keep the expected user experience, we need to tweak and adjust our algorithm. This new variant uses a 120dpi instead of 96dpi as it's step size.
Until further testing has been done and likely more tweaks have been made, this will remain a draft.

kms: Try to calculate dpi and scale factor (Take 2)

---

Cargo.toml

Using `lto = "thin"` seems to increase incremental build time when a file is `touch`ed from about 3 seconds to almost 30.
I'm not sure if this helped with anything, but there are probably better ways to improve `dev` performance than enabling LTO.

Don't enable thin LTO in `dev` profile

---

src/wayland/handlers/toplevel_management.rs

Previously, alt-tab wouldn't actually focus a window if it was on another output, since the active output/workspace was unchanged.
We need to move the cursor if we activate a window on another output.

toplevel-management: Set active output if changed, and move cursor

---

src/shell/focus/mod.rs

This seems to work, but produces a flood of events. Smithay probably need a method to update focus without producing events unless a surface is entered.
Instead of `time: 0`, this and other synthesized events should probably use `CLOCK_MONOTONIC`. It seems libinput does document that it uses that.

Update pointer focus before motion occurs

---

Cargo.lock
Cargo.toml
src/input/mod.rs
src/shell/focus/mod.rs
src/shell/grabs/menu/default.rs
src/shell/grabs/moving.rs
src/wayland/handlers/toplevel_management.rs

Update to https://github.com/Smithay/smithay/pull/1509, and adopt a similar change.

Use monotonic time instead of `0` for motion events

---

src/input/mod.rs
src/shell/element/stack.rs
src/shell/element/window.rs
src/shell/grabs/menu/default.rs
src/shell/mod.rs
src/shell/seats.rs
src/wayland/handlers/xdg_shell/mod.rs
src/xwayland.rs

Fixes #686
Previously when doing Super+{Left,Right} Click the compositor would still send the button event to the client, for left click this didn't cause issues most of the time but for right click this caused many issues because it would usually open a context menu which would cause the resize to stop immediately.
This PR fixes the issue by not sending any button events if the logo key is held.

Fix button events being sent when super is held

---

src/wayland/handlers/screencopy/render.rs

It seems we allocate a new `GlesRenderbuffer` every time we screencopy to an shm buffer.
We probably should use a more complicated approach to do proper damage tracking without any unnecessary copies, and re-using the GPU buffer, but as long as this allocates a buffer the age of that buffer should be treated as `0`.
Fixes corruption in cosmic-workspaces when shm screencopy is used. (For instance, when Cosmic is run with software rendering.)

screencopy: Use buffer age of `0` for render to temporary buffer

---

Cargo.lock
Cargo.toml
src/shell/mod.rs
src/state.rs
src/wayland/handlers/compositor.rs
src/wayland/handlers/foreign_toplevel_list.rs
src/wayland/handlers/mod.rs
src/wayland/handlers/xdg_shell/mod.rs
src/xwayland.rs

Seems to be working, testing with https://github.com/Smithay/client-toolkit/pull/465.

Add `ext-foreign-toplevel-list-v1` protocol

---

src/backend/kms/surface/mod.rs
src/backend/render/element.rs
src/config/mod.rs
src/shell/element/mod.rs
src/shell/focus/mod.rs
src/shell/layout/floating/mod.rs
src/shell/layout/tiling/mod.rs
src/shell/mod.rs
src/shell/workspace.rs
src/wayland/handlers/compositor.rs
src/wayland/protocols/workspace.rs

This refactor removes lifetimes where the compiler can imply them, making function signatures a bit simpler.
Example:
```
fn update_active<'a, 'b>(&mut self) {
```
becomes:
```
fn update_active(&mut self) {
```
Resolves 2 types of clippy warnings, in 25 instances:
1. https://rust-lang.github.io/rust-clippy/master/index.html#/extra_unused_lifetimes
2. https://rust-lang.github.io/rust-clippy/master/index.html#/needless_lifetimes

Cleanup: remove unnecessary lifetimes

---

Cargo.lock
Cargo.toml
cosmic-comp-config/src/lib.rs
src/config/mod.rs
src/input/mod.rs
src/shell/mod.rs
src/state.rs
src/xwayland.rs

Adds a "X11 windows handle scaling on their own"-option similar to KDE.
Draft until cosmic-session and cosmic-settings PRs are done and the necessary smithay changes are merged.

Xwayland de-scaling

---

src/backend/winit.rs
src/input/mod.rs
src/shell/mod.rs
src/wayland/handlers/screencopy/render.rs
src/wayland/handlers/toplevel_management.rs
src/xwayland.rs

Removes typecasts where the variable is already that type, e.g.:
```
let offset = data.offset as i32;
let width = data.width as i32;
let height = data.height as i32;
let stride = data.stride as i32;
```
these fields are already `i32`, so `as i32` can be removed.
This resolves 18 instances of this warning.
Found with clippy lint:
https://rust-lang.github.io/rust-clippy/master/index.html#/unnecessary_cast

Cleanup: remove unnecessary casting

---

cosmic-comp-config/src/input.rs
cosmic-comp-config/src/lib.rs
src/backend/render/mod.rs
src/config/mod.rs
src/input/mod.rs
src/shell/element/window.rs
src/shell/focus/mod.rs
src/shell/grabs/menu/default.rs
src/shell/grabs/menu/mod.rs
src/shell/grabs/moving.rs
src/shell/layout/floating/mod.rs
src/shell/layout/tiling/mod.rs
src/shell/mod.rs
src/shell/seats.rs
src/shell/workspace.rs
src/state.rs
src/wayland/handlers/compositor.rs
src/wayland/handlers/toplevel_management.rs
src/wayland/handlers/xdg_activation.rs
src/wayland/handlers/xdg_foreign.rs
src/wayland/handlers/xdg_shell/mod.rs
src/xwayland.rs

- resolves #564 
Still learning the codebase, and right now this is just some boilerplate. As mentioned in 564 there would be 3 mouse focus policies:
- focus requires click (current and default)
- focus changes when mouse moves to a new output
- focus follows mouse (sloppily or lazily)
The first requires 0 changes and the code for click to focus still needs to execute when following one of the other policies (if there is a delay before window focusing, clicking a window should still focus it.). So the only place code needs to be added is in the two `todo!()`s currently in `src/input/mod.rs`. I think  I can probably extract the contents of [this conditional](https://github.com/pop-os/cosmic-comp/blob/713ac470aa992712b105116e44c338986d591782/src/input/mod.rs#L755) into a function, with some …

Configurable mouse focus

---

Cargo.lock
Makefile
cosmic-comp-config/src/lib.rs
data/tiling-exceptions.ron
src/config/mod.rs
src/shell/layout/mod.rs
src/shell/mod.rs

This moves out the hard coded tiling exceptions into a new separate config file under CosmicComp

Move tiling exceptions to configuration file

---

src/backend/render/cursor.rs
src/shell/element/stack.rs
src/shell/element/window.rs
src/shell/grabs/moving.rs
src/shell/layout/tiling/grabs/resize.rs
src/shell/seats.rs
src/state.rs
src/wayland/handlers/seat.rs
src/xwayland.rs

when a cursor is requested it first renders any Surface cursors, then it renders the named cursors giving priority to the cursors set by the `set_shape` function.
surprising behaviour to me at least is, that it gives priority to Hidden and Surface cursors over the cursors set by `set_shape`, but since that also was the old behaviour i didn't change it without getting feedback first.
i replaced the [manual cursor cache insertion on startup](https://github.com/pop-os/cosmic-comp/blob/79ae56c601176f179870f75719416dbabe3d01d9/src/backend/render/cursor.rs#L259-L310) (because i thought it was silly to repeat this for 34 cursors) and replaced it with a function that loads [the cursors on demand](https://github.com/pop-os/cosmic-comp/blob/dd9adc0616cc692f4707cd92178237f0979196b8/src/backend/render …

implement cursor-shape-v1

---

Cargo.lock
Cargo.toml
src/xwayland.rs

This fixes the issue where X11 windows freeze and can't be closed when Xwayland dies.
Requires https://github.com/Smithay/smithay/pull/1527 and a calloop release with https://github.com/Smithay/calloop/pull/208 (it seems https://github.com/Smithay/calloop/commit/0ab5cc22ed224d0fabf6e901b0d0a58ea494357a fixed an issue, but https://github.com/Smithay/calloop/commit/86c6713980ce08e3b2111efb9056aca9fd5f8d9 broke things).

Destroy `X11Wm` when we lose connect to X server

---

data/tiling-exceptions.ron

Part of https://github.com/pop-os/cosmic-files/issues/335

Add com.system76.CosmicFilesDialog as floating window exception

---

flake.nix
rust-toolchain.toml

There are multiple issues with `flake.nix`.
1. `rust-src` is missing in `rust-toolchain.toml`.
Because of that, Rust Analyzer fails to resolve `std`, rendering RA pretty much unusable. 
(Zed log)
```
[WARN  project] Language server rust-analyzer-2024-09-02 (id 1) status update: Workspace `~/cosmic/cosmic-comp/Cargo.toml` has sysroot errors: can't load standard library from sysroot
{sysroot_path}
(discovered via `rustc --print sysroot`)
try installing the Rust source the same way you installed rustc
```
`flake.nix` imports rust toolchain from it:
https://github.com/pop-os/cosmic-comp/blob/52280e9823506a480248e84caaf7545426a871c8/flake.nix#L26 
2. When running in Wayland session in NixOS, `cosmic-comp` fails since `libwayland-egl.so` is missing in runtime.
```
2024-09-04T12:46:55.406051Z …
```

fix: flake.nix under NixOS

---

Cargo.lock
Cargo.toml
src/backend/kms/mod.rs
src/backend/winit.rs
src/backend/x11.rs
src/config/mod.rs
src/input/mod.rs
src/shell/layout/mod.rs
src/shell/layout/tiling/grabs/swap.rs

Requires https://github.com/Smithay/smithay/pull/1533. If the `input_intercept` changes there are controversial, this could instead use a a few more arguments, or something involving `input_intercept`/`input_forward` instead of `input` (but that's probably not simpler).
https://github.com/pop-os/cosmic-comp/pull/465 will require some additional logic here to filter out the key grabs. I don't really want this to get *more* complicated so a wanted to try splitting things up first. Just moving the callback to a method is a start, though more could be improved.

Split off `KeyboardHandle::filter` callback to separate method

---

Cargo.lock
Cargo.toml
src/shell/element/surface.rs
src/shell/mod.rs
src/state.rs
src/wayland/handlers/compositor.rs
src/wayland/handlers/foreign_toplevel_list.rs
src/wayland/handlers/toplevel_info.rs
src/wayland/handlers/toplevel_management.rs
src/wayland/handlers/xdg_shell/mod.rs
src/wayland/protocols/mod.rs
src/wayland/protocols/overlap_notify.rs
src/wayland/protocols/toplevel_info.rs
src/wayland/protocols/toplevel_management.rs
src/xwayland.rs

Swallows up the foreign-toplevel-list protocol handling as well, to be able to guarantee event-order between the cosmic-toplevel-info protocol and foreign-toplevel-list (e.g. it's `done`-event).
Untested, but this should basically work..

toplevel-info/mgmt: Update to v2/v3

---

src/backend/kms/device.rs
src/backend/kms/drm_helpers.rs
src/backend/kms/mod.rs
src/config/mod.rs
src/shell/mod.rs
src/state.rs

This works, but with multiple outputs results in overlapping outputs in the display configuration (which has weird effects). So I guess that will also need a change go consider the orientation.

Set default output transform based on DRM `panel orientation`

---

src/input/mod.rs

input: Treat pointer-shortcuts as potentially inhibited

---

src/shell/grabs/moving.rs

when i implemented the cursor-shape-v1 protocol in #844 i didn't notice that the previous `CursorShape::Grab` actually mapped to `CursorIcon::Grabbing` instead of `CursorIcon::Grab`. this fixes that "regression".

use `Grabbing` cursor instead of `Grab` cursor

---

Cargo.lock
src/shell/element/resize_indicator.rs
src/shell/element/stack/tab.rs
src/shell/element/stack/tab_text.rs
src/shell/element/stack/tabs.rs
src/shell/element/stack_hover.rs
src/shell/element/swap_indicator.rs
src/shell/element/window.rs
src/shell/grabs/menu/mod.rs
src/shell/mod.rs
src/utils/iced.rs

This makes the menu match other context menus in COSMIC, and ensures some spacing between the shortcut and title. Tried to make the menu change with Density (hence the libcosmic update), but it didn't seem to change anything, regardless of the way of incorporating the spacing variables.
(Edit: Not sure why the text color of the title is the same as the shortcut. I've tried switching the title back to how it was, but it didn't change. But this is also the case in menus in apps)
Also tweaked the resize indicators for better styling. The right indicator still gets cut off slightly at smaller window widths, but not sure why that happens. 
The centering of the SSD header title has a minor issue in some apps at minimum widths (only saw it on GitHub desktop so far; other apps have higher minimum …

Fix context menu styling

---

src/shell/focus/mod.rs

i'm not sure if you would want to put this behind a config, but i don't know if the cursor warping to the top left of a window is ever the better option over warping to the center, but i can config it if desirable.
i removed the `if is_some()` and then `unwrap()` thing, because `Rectangle` is copy and not borrowed anyway, but i don't exactly know why this was here so i can just revert it if necessary.

warp cursor to center of window for `cursor_follows_focus`

---

src/shell/grabs/menu/mod.rs

Just makes the context menu use `@radius_s` for the corner radius, to match the highlight for items inside.
I also tried to make the stack header do the same, but it didn't seem to pick up roundness changes.

[Menu] Use corner radius from theme

---

src/shell/mod.rs
src/shell/workspace.rs
src/wayland/protocols/screencopy.rs
src/wayland/protocols/toplevel_info.rs
src/wayland/protocols/toplevel_management.rs
src/wayland/protocols/workspace.rs

I've been annoyed by how this adds an empty initial workspace which ends up focused instead of one of the non-empty ones. For some reason that's still happening... I also see some other things that could be fixed.
It seems there also is (sometimes?) an issue where a window becomes unresponsive after being moved. Probably a frame callback issue... I need to look into that more.

Fixes for behavior when workspaces are moved back to on output on hotplug

---

src/backend/render/element.rs
src/backend/render/mod.rs
src/input/mod.rs
src/shell/element/mod.rs
src/shell/element/stack.rs
src/shell/element/surface.rs
src/shell/element/window.rs
src/shell/focus/mod.rs
src/shell/focus/order.rs
src/shell/grabs/moving.rs
src/shell/layout/floating/mod.rs
src/shell/layout/tiling/mod.rs
src/shell/mod.rs
src/shell/workspace.rs

Draft because this needs more testing.
In theory this should fix:
- https://github.com/pop-os/cosmic-comp/issues/769
- https://github.com/pop-os/cosmic-comp/issues/698
- and probably some more similar issues
Essentially this tries to use common code for iterating through all of the surfaces/clients/whatever that can be rendered and receive input.
Unfortunately this means dropping `SplitRenderElements`, as that was/is a source of disagreement between the input-code (which doesn't have a similar method) and the render-code.
As such this duplicates a bit of code, but usually the popup code path is much shorter anyway, so we introduce separate code paths for popups and toplevels all over.
This also cleans up some of the code introduced as part of the focus-follows-cursor (and vise versa) …

Refactor and unify {render, input}-order

---

Cargo.lock
Cargo.toml
src/backend/kms/mod.rs
src/backend/kms/surface/mod.rs
src/input/mod.rs
src/state.rs
src/wayland/handlers/mod.rs
src/wayland/handlers/output_power.rs
src/wayland/protocols/mod.rs
src/wayland/protocols/output_power.rs

This works to set DPMS on or off. It still needs to track the DPMS state and send events to clients when the mode changes. And otherwise be cleaned up a bit.
Components like `cosmic-greeter` may make use of this.
This can be tested with the below code (which also works on Sway):
```rust
use std::{env, process};
use wayland_client::{
delegate_noop,
globals::{registry_queue_init, GlobalListContents},
protocol::{wl_output, wl_registry},
Connection, Dispatch, Proxy, QueueHandle,
};
use wayland_protocols_wlr::output_power_management::v1::client::{
zwlr_output_power_manager_v1, zwlr_output_power_v1,
};
struct State;
fn main() {
let mode = match env::args().skip(1).next().as_ref().map(|x| x.as_str()) {
Some("on") => zwlr_output_power_v1::Mode::On,
Some("off") => zwlr_output_power_v1::Mode::Off, …
```

DPMS with `wlr-output-power-management-unstable-v1` protocol

---

Cargo.lock
Cargo.toml
src/config/mod.rs
src/input/mod.rs
src/state.rs
src/wayland/handlers/atspi.rs
src/wayland/handlers/mod.rs
src/wayland/protocols/atspi.rs
src/wayland/protocols/mod.rs

This works with the `receive` example of `reis` using `LIBEI_SOCKET=/tmp/atspi-ei-kb.socket`. I've also worked on changes to at-spi2-core, so I'll now be able to try testing it...
If a version of this is ultimately used, it will need a secure way to pass the socket to accessibility tools. Putting it in `/tmp` is a placeholder.

Add `cosmic_atspi_v1` protocol

---

src/shell/grabs/moving.rs

This commit changes the snapping indicator's thickness to match the active window hint, per design recommendation by Maria. The thickness for this outline never goes under 1, also per Maria's spec.

design: use active_window_hint as the thickness for floating window snap outline

---

src/state.rs

Previously, changing the resolution, scale, or orientation of a display left tiling layouts that don't fill the screen and/or extend off of the screen area, until an action like opening a window makes it recalculate window positions.
Now this is done immediately when the output configuration changes.
Perhaps we should consider if we want a different animation for things like rotating a screen, but the current behavior isn't too bad.
For floating layouts, `refresh` already remaps windows that are out of bounds for the output, so this doesn't change that. Perhaps decreasing the resolution (or moving to a lower resolution output) should try to reduce the window size. But the current behavior generally seems okay.

Recalculate tiling layout on change of display configuration

---

src/state.rs
src/wayland/protocols/output_configuration/mod.rs

`Output` in Smithay doesn't track if the output still exists, other than based on whether or not it has strong references. Which doesn't seem to be working correctly.
There may be leaked strong references to `Output`s somewhere, and maybe Smithay should track if an output is still valid, generally when it is exposed as a Wayland global
(https://github.com/Smithay/smithay/issues/1584). But a check like this works for now.
Addresses https://github.com/pop-os/cosmic-comp/issues/985.

Use new primary scanout output if old output is disabled

---

src/state.rs

If an individual window was being screencast, and that window was not visible, for example because it was minimized, that window would only be rendered every 995ms, which did not look good on the screencast.
Now, non-visible windows with active screencopy sessions, as well as windows that are mapped on non-visible workspaces with active screencopy sessions, are rendered every 1/60th of a second, which matches the frame rate of the video produced by xdg-desktop-portal-cosmic.  In future, it might be good to let screencopy clients suggest a redraw rate for captured windows.
---
I've tested that minimized windows and hidden windows in a stack can now be screencast smoothly.  I haven't tested screencasts of unfocused workspaces or pointer cursor sessions, because I don't know of clients for …

Unthrottle windows in screencopy sessions

---

Cargo.lock
Cargo.toml
src/backend/kms/device.rs
src/backend/kms/drm_helpers.rs
src/backend/kms/mod.rs
src/backend/kms/surface/mod.rs
src/backend/winit.rs
src/backend/x11.rs
src/config/mod.rs
src/utils/prelude.rs
src/wayland/handlers/data_device.rs
src/wayland/handlers/output_configuration.rs
src/wayland/protocols/output_configuration/handlers/cosmic.rs
src/wayland/protocols/output_configuration/handlers/wlr.rs
src/wayland/protocols/output_configuration/mod.rs

Draft until cosmic-randr and cosmic-settings are ready

Adaptive VRR support

---

src/wayland/handlers/screencopy/render.rs

This meant that, for windows that were not fully opaque, there was no way to capture their transparency.  No way to put a window with transparency on top of a background in OBS, for example.
(Thanks @tranquillity-codes for teaching me about pre-multiplied alpha when I was going down the wrong track)

screencopy: don't force opaque window backgrounds

---

src/dbus/mod.rs
src/main.rs

On systems without systemd, use zbus to update D-Bus activation environment with `WAYLAND_DISPLAY` and `DISPLAY` variables.
Fixes #1037

main: Update D-Bus activation environment also on non-systemd systems

---

src/wayland/handlers/xdg_activation.rs

If the activated element is outside the current workspace, its workspace should be set to urgent

fix: activation of an element outside the current workspace

---

src/wayland/protocols/output_configuration/handlers/cosmic.rs
src/wayland/protocols/output_configuration/handlers/wlr.rs

Fixes https://github.com/pop-os/cosmic-epoch/issues/1341.

Fix panic with mirroring

---

src/wayland/protocols/toplevel_info.rs

Instead of looking for toplevel handles for the client, look for toplevel handles for the specific global instance.

toplevel-info: Fix behavior with multiple instances of global

---

src/state.rs
src/wayland/protocols/output_configuration/mod.rs

This should fix an issue where output hotplug can sometimes cause clients (including XWayland) to crash with a protocol error trying to bind the output.
Using a timer doesn't seem ideal, but seems to be the correct way to do this at present. Wlroots `wlr_global_destroy_safe` is basically the same as this.
Adding a `LoopHandle` argument to `OutputConfigurationState::new` seems awkward, but maybe better than a handler method for removing globals. (`IdleNotifierState::new` also takes a `LoopHandle`). Perhaps Smithay could provide some kind of helper for this.

When removing output global, use `disable_global`, remove with timer

---

src/shell/element/mod.rs
src/shell/element/stack.rs
src/shell/element/surface.rs
src/shell/element/window.rs
src/shell/layout/mod.rs
src/xwayland.rs

This fixes several things:
- The xwayland code previously incorrectly used the SSD_HEIGHT (for Windows) even when the X11 surface was in a stack
- The SSD_HEIGHT was defined in surface.rs, even though rendering serverside decorations is done in the window/stack
Rename (min|max)_size to (min|max)_size_without_ssd in CosmicSurface and make it act accordingly
Add a new (min|max)_size() in CosmicWindow and CosmicStack, which takes the surface's (min|max)_size and adds the decorations.
Change all callers to use (min|max)_size() from the window or stack respectively, except is_dialog() where it does not matter.

refactor(shell/element): refactor how decorations height is accessed

---

src/shell/mod.rs

Currently, after untoggling sticky while maximized, `MaximizedState::original_layer` remains with value `ManagedLayer::Sticky`, which can lead to a crash when unmaximizing the window by reaching an `unreachable!()` statement.
Closes #1074

Fix sticky toggle crashes on maximized windows

---

src/input/mod.rs
src/shell/seats.rs

This fixes #1104
LEDs on keyboard will now update to match the compositor state when they're plugged in.

Update leds when devices are added

---

Cargo.lock
Cargo.toml
src/backend/kms/surface/mod.rs
src/backend/render/element.rs
src/backend/render/mod.rs
src/input/mod.rs
src/shell/element/mod.rs
src/shell/element/stack.rs
src/shell/element/window.rs
src/shell/grabs/menu/mod.rs
src/shell/grabs/moving.rs
src/shell/layout/floating/grabs/resize.rs
src/shell/layout/floating/mod.rs
src/shell/layout/tiling/mod.rs
src/shell/mod.rs
src/shell/seats.rs
src/shell/workspace.rs
src/utils/geometry.rs
src/utils/iced.rs
src/utils/prelude.rs
src/utils/tween.rs
src/wayland/handlers/screencopy/render.rs
src/wayland/handlers/toplevel_management.rs
src/wayland/handlers/xdg_shell/popup.rs
src/wayland/protocols/overlap_notify.rs
src/wayland/protocols/screencopy.rs
src/wayland/protocols/toplevel_management.rs
src/xwayland.rs

Depends on https://github.com/Smithay/smithay/pull/1621.
Annoying to update, but overall a little bit better.
Some of these `Rectangle::new` calls should probably be written in a way that doesn't construct new `Point`/`Size` instances from scalars and uses higher-level operations that preserve coordinate space, but this doesn't change that for now. (If we can move Smithay to `euclid` that should have a few more useful methods to clean up things like that too.)

Migrate away from `Rectangle::from_loc_and_size`

---

flake.nix

Trying to `cargo run --release` inside the flake.nix development shell (through `nix develop `command) yielded this error:
```
❯ cargo run --release
Compiling tiny-xlib v0.2.3
Compiling libudev-sys v0.1.4
Compiling libseat-sys v0.1.7
Compiling x11-dl v2.21.0
Compiling libdisplay-info-sys v0.2.0
Compiling smithay v0.3.0 (https://github.com/smithay//smithay?rev=9fbc9fb#9fbc9fbb)
Compiling cosmic-comp v0.1.0 (/home/cenk/cosmic-comp)
error: failed to run custom build command for `libdisplay-info-sys v0.2.0`
```
It was fixed by adding the missing `libdisplay-info` library into the flake buildInputs.

fix: add missing libdisplay-info library into flake.nix

---

src/backend/kms/mod.rs
src/wayland/handlers/compositor.rs
src/wayland/handlers/drm_syncobj.rs
src/wayland/handlers/mod.rs

Based on https://github.com/Smithay/smithay/pull/1356.
I think the blocker logic should be correct for handling acquire points (if I properly understand the transaction system in Smithay). Though I don't see rendering issues with Mesa git when the blocker is removed... maybe it needs to be tested with something heavier than vkcube. (Or is there something still forcing implicit sync?).
The logic I added in Smithay for signaling releases may be a little less correct. Though maybe not more incorrect that how buffer releases are currently handled? (If I understand DRM correctly, with direct scanout we should make sure not to release until we've committed a new buffer and are sure the display controller won't want to read the buffer.)
We'll be able to test more when the next Nvidia driver is …

Add `linux-drm-syncobj-v1` protocol

---

src/shell/element/mod.rs
src/shell/element/surface.rs
src/shell/layout/floating/grabs/resize.rs
src/shell/layout/floating/mod.rs
src/shell/layout/tiling/blocker.rs
src/shell/layout/tiling/grabs/resize.rs
src/shell/layout/tiling/mod.rs
src/wayland/handlers/toplevel_info.rs
src/wayland/protocols/toplevel_info.rs

Uses a couple of new smithay additions to finally fix our TilingLayout Blocker code (thanks @YaLTeR !), throttles resizes (again thanks to niri for some inspiration) and finally tracked down why the animation code breaks in some cases causing flicker (which should now be fixed).

Overhaul resizing

---

src/wayland/handlers/toplevel_management.rs

Addresses https://github.com/pop-os/cosmic-workspaces-epoch/issues/89, https://github.com/pop-os/cosmic-workspaces-epoch/issues/41, though cosmic-workspaces should probably show minimized windows and stacks in some way (the latter would also need a new protocol for stack information and management).

toplevel-info: Handle minimized windows, and windows in stacks, in `move_to_workspace`

---

src/shell/mod.rs

Partly fixes https://github.com/pop-os/cosmic-workspaces-epoch/issues/83, but it seems like there's at least one other issue with workspaces not being removed when they should be.
The if condition got a bit complicated here, so I've split it up and inverted the condition.

shell: Remove last workspace if it follows empty active workspace

---

src/backend/kms/surface/mod.rs

Also applicable to https://github.com/pop-os/cosmic-comp/pull/1058.
Looks like damage tracking for mirroring with output transforms isn't quite right either (before or after this) so some more fixes are needed.

Fixes for transformed outputs with mirroring

---

src/shell/mod.rs
src/wayland/handlers/compositor.rs
src/wayland/handlers/layer_shell.rs
src/wayland/handlers/toplevel_management.rs
src/wayland/handlers/xdg_shell/mod.rs
src/xwayland.rs

Similar to how we handle fullscreen-requests for unmapped windows.
While I am at it, this also refactors pending windows and layers a bit to make handling nicer. It also allows to unset the fullscreen state on pending windows again, which should be legal according to the protocol, but wasn't handled correctly previously.

shell: Handle maximize requests before commit

---

src/backend/mod.rs
src/config/mod.rs

When changing keyboard layout, modifier state of keyboard resets to default. This happens here  `keyboard.set_xkb_config(..)`. In turn this call leads to `KeyboardHandle::update_xkb_state` call, which in turn executes such code
```
let mut state = xkb::State::new(&keymap);
for key in &internal.pressed_keys {
state.update_key(*key, xkb::KeyDirection::Down);
}
```
To make sure, that numlock/capslock state is not modified, we read old state, and if needed active those modifiers again.

Reactivated num/caps-lock upon keyboard layour change

---

cosmic-comp-config/src/lib.rs
src/config/mod.rs
src/input/mod.rs
src/shell/element/stack.rs
src/shell/element/window.rs
src/shell/grabs/menu/default.rs
src/shell/grabs/moving.rs
src/shell/layout/floating/grabs/resize.rs
src/shell/layout/floating/mod.rs
src/shell/mod.rs
src/wayland/handlers/xdg_shell/mod.rs
src/xwayland.rs

This is a feature that KDE has called "Snap Zones" which I find to be very useful for organizing floating layouts (especially small widgets like the Spotify miniplayer, demonstrated in the video).
When resizing or moving a floating/sticky window, any edge that gets too close to one of the currently active output's edges will be snapped into the output's edge, mitigating any pixel-perfect movements you would have to do otherwise to get window edges to align properly.
https://github.com/user-attachments/assets/9ea74bf9-af80-4e3c-a210-8e610c73a50e

feat: Snap Window Edges to Close Output Edges

---

cosmic-comp-config/src/lib.rs

This will allow NumlockState to be used as a radio value in cosmic-settings.

Derive Eq for NumlockState

---

Cargo.lock
Cargo.toml
src/shell/mod.rs
src/shell/workspace.rs
src/wayland/handlers/toplevel_management.rs
src/wayland/handlers/workspace.rs
src/wayland/protocols/image_source.rs
src/wayland/protocols/toplevel_info.rs
src/wayland/protocols/toplevel_management.rs
src/wayland/protocols/workspace/cosmic.rs
src/wayland/protocols/workspace/cosmic_v2.rs
src/wayland/protocols/workspace/ext.rs
src/wayland/protocols/workspace/mod.rs

https://github.com/pop-os/cosmic-protocols/pull/51
(Partly) working, but needs a couple fixes, and update to toplevel-info/toplevel-management (both here and in cctk).

`cosmic-workspace-v2` protocol

---

src/wayland/protocols/workspace/cosmic_v2.rs

I forgot to handle these after I added them to destructors to the protocol.
I wish we had exhaustiveness checking here...

fix(protocol/workspace): Handle cosmic-workspace-v2 destroy requests

---

src/shell/layout/floating/mod.rs
src/utils/iced.rs

Fixes https://github.com/pop-os/cosmic-comp/issues/1287
`smithay::desktop::Space` used in our floating layout, only sends out `output_enter` events grouped on `refresh`. This is somewhat problematic with our new throttling, as it can cause entire server-side widgets to not show up until after the next refresh.
We barely map a larger count of windows at once anyway, so lets just make sure to force a refresh of the space (only) after mapping.
Additionally our iced integration also (de-)allocates buffers on refresh, which is why `output_leave` already called that, but `output_enter` didn't. Lets fix that, so we immediately get new contents on `output_enter` without having to make sure that we also call `refresh` on each and every server-side rendered widget. A second refresh call will not …

Address some visible jank from refresh throttling

---

src/shell/mod.rs
src/wayland/protocols/workspace/cosmic.rs
src/wayland/protocols/workspace/cosmic_v2.rs
src/wayland/protocols/workspace/ext.rs
src/wayland/protocols/workspace/mod.rs

A couple changes to how `output_add` and `output_remove` handle workspace moves. (Plus a minor improvement to the workspace protocol.)
I think this fixes the issues where output hotplug can results in 0 or 2 workspaces being shown as active instead of 1, and also addresses another case where hotplug results in an empty focused workspace followed by other workspaces (that one's not technically a bug, but I think this is better).

Workspace related fixes/improvement

---

src/backend/render/mod.rs
src/shell/grabs/moving.rs
src/shell/layout/floating/mod.rs
src/shell/layout/tiling/mod.rs

I noticed that the active window hint scales more than the rest of the UI, so I tried removing the seemingly special treatment given to border scaling:
```rust
let thickness = (thickness as f64 * scale).round() as u8;
let radius = (radius as f64 * scale).round() as u8;
```
And now it scales in line with everything else.

fix: Remove unnecessary scaling of borders

---

src/backend/render/mod.rs

Apparently in Rust 2024, the inferred type here would be `!`, which doesn't implement `Default`. Explicitly use `()` instead.
https://doc.rust-lang.org/nightly/edition-guide/rust-2024/never-type-fallback.html

Fix `dependency_on_unit_never_type_fallback` warning on latest Rustc

---

Cargo.lock
Cargo.toml
src/input/actions.rs
src/input/mod.rs
src/shell/element/stack.rs
src/shell/element/window.rs
src/shell/grabs/menu/default.rs
src/shell/mod.rs
src/shell/workspace.rs
src/state.rs
src/wayland/handlers/xdg_activation.rs
src/wayland/handlers/xdg_shell/mod.rs
src/xwayland.rs

Requires https://github.com/Smithay/smithay/pull/1676.
This changes two things:
* `Workspace::is_empty` no longer checks if there are activation tokens,
but a separate `Workspace::can_auto_remove` checks if the workspace is
empty and has no activation tokens.
- When we add workspace pinning, that can also be checked there.
* `Workspace` no longer contains a `pending_tokens` list that is updated
on `refresh`. Instead, `can_auto_remove` takes the xdg activation
state as an argument.
Since `Workspace::refresh` normally is run for focused workspaces, this
fixes allowing non-focused workspaces to be removed when an activation
token expires. It seems generally good to avoid tracking the activation
tokens in two places, and this is probably more efficient than needing
to refresh in more places. …

Improve handling of XDG activation tokens in shell

---

src/backend/kms/surface/timings.rs

Fixes #1062
I'm not sure if this is the right approach, I'm not sure why this is sometimes overflowing (and why it happens on some platforms way more often than others), and there are probably(?) other areas where overflow can occur... but this patch did fix the crash for me on a ARM device (using the SDM845 SOC)

kms/surface/timings: handle potential overflow when calculating avg frametime

---

cosmic-comp-config/src/lib.rs
src/backend/mod.rs
src/backend/render/mod.rs
src/config/mod.rs
src/input/actions.rs
src/input/mod.rs
src/shell/focus/order.rs
src/shell/grabs/menu/mod.rs
src/shell/mod.rs
src/shell/zoom.rs
src/state.rs
src/utils/geometry.rs
src/utils/prelude.rs
src/wayland/handlers/a11y.rs

a11y/zoom: Various fixes

---

cosmic-comp-config/src/workspace.rs

cosmic-comp-config uses an extra function and #[serde(default = ...)] macro rather than simply applying the default at the enum level. This aligns better with the code style of TileBehavior in lib.rs

config: Refactor WorkspaceLayout to use the Default macro

---

src/backend/kms/device.rs
src/config/mod.rs
src/shell/mod.rs
src/shell/workspace.rs
src/utils/prelude.rs

EDID matching in https://github.com/pop-os/cosmic-comp/pull/1252, but for output stacks.
It seems better to add here first (where it isn't persisted) and overhaul the on-disk format for output configuration along with pinned workspace persisting, which will also need this.
For persistent workspaces, I think it makes sense not to persist the whole output stack, but only the last output a workspace was explicitly placed on (where it was created, or moved to by the user). Though there may be edge cases where this is undesirable and confusing. (Which is also a potential problem for any other alternative.)
So when a workspace is moved explictly by the user, the output stack is cleared. And the earliest output in the stack is where it was placed explictly.
Getting the behaviors right when …

EDID matching for output stack

---

cosmic-comp-config/src/lib.rs

Requested by @WatchMkr.
May be less confusing for users than having some functionality work but not others by default. This way, something is clearly not working and they'll hopefully know to look the setting up so they can learn all the available options and their security implications.

Change default X11 eavesdropping to None

---

Cargo.lock
Cargo.toml
cosmic-comp-config/src/lib.rs
src/config/mod.rs
src/state.rs
src/wayland/handlers/output_configuration.rs
src/wayland/protocols/output_configuration/handlers/cosmic.rs
src/wayland/protocols/output_configuration/mod.rs
src/xwayland.rs

Seems to work surprisingly well, but some apps don't match the fractional scale factor (how would they, given this was never supported by any toolkit).
Many will increase their font size with the dpi value (Qt apps) or be slightly off (in the worse case up to 50% until the nearest integer value), appearing larger/smaller accordingly (e.g. GTK3 apps).
Others like Steam can scale to whatever and still don't seem to get it completely right (window is slightly too small by default), but given the custom toolkit doesn't fit into the desktop, it looks correct.
It certainly works much much better with games, which now see the correct resolution on the monitor with the highest scaling value (no matter with fractional or not), while only the others are slightly off and will be scaled accordingly. …

Fractional Xwayland scaling

---

src/backend/render/cursor.rs
src/xwayland.rs

This fixes https://github.com/pop-os/cosmic-comp/issues/875 and some tiny cursor in Xwayland when any but the "compatibility"-scaling setting is choosen.
~~However I cannot figure out why chromium based (so chrome + electron) flatpak apps don't respect it, when running under X11. Works just fine, when they are installed from .deb-files. Presumably they read the xcursor size from a different source, as I confirmed the xsettings propagate correctly into the sandbox, but the chromium source code isn't exactly straight forward.~~ Seems to be a packaging issue.

Various cursor fixes

---

Cargo.lock
Cargo.toml
cosmic-comp-config/Cargo.toml
cosmic-comp-config/src/lib.rs
cosmic-comp-config/src/output.rs
cosmic-comp-config/src/workspace.rs
src/config/mod.rs
src/shell/mod.rs
src/shell/workspace.rs
src/wayland/handlers/workspace.rs
src/wayland/handlers/xdg_activation.rs
src/wayland/protocols/workspace/cosmic_v2.rs
src/wayland/protocols/workspace/ext.rs
src/wayland/protocols/workspace/mod.rs

Initial compositor-side prototype for https://github.com/pop-os/cosmic-workspaces-epoch/issues/108, using https://github.com/pop-os/cosmic-protocols/pull/48.
This adds a pinned flag for workspaces, which prevents the workspace from being removed automatically when empty, and allows a new workspace after it.
This does not yet persist pinned workspaces. Or allow re-ordering workspaces. We probably want to persist pinned workspaces by monitor and order, with names.

Initial support for workspace pinning and moving

---

Cargo.lock
Cargo.toml
src/backend/kms/device.rs
src/backend/kms/surface/mod.rs
src/backend/kms/surface/timings.rs
src/backend/render/mod.rs
src/main.rs
src/shell/element/stack.rs
src/shell/element/window.rs
src/utils/iced.rs

Draft as this needs more testing on different systems.
This touches the frame scheduling logic again, but this time all profiled with tracy, so that we actually have some data:
1. According to kwin, mesa drivers return from `page_flip`/`commit` once the commit is staged for the next vblank. So we can use the time until submission (not presentation) to optimize our latency by moving closer, if we finish submission early. Waiting for presentation was somewhat borked anyway, as that depends on the refresh rate, so most likely we were rendering asap anyway.
2. This also introduces a workaround for nvidia cards, where this doesn't seem to help at all. Especially on multi-gpu setups submission might take ages, while we wait for the render operation to complete and we don't have a feedback …

Profiling / Performance fixes

---

data/tiling-exceptions.ron

The Tor Browser launches with a specific dimension to avoid browser fingerprinting[0]. Do not tile the Tor Browser for this reason.
[0]: https://tb-manual.torproject.org/anti-fingerprinting/#letterboxing

Add `Tor Browser` as floating window exception

---

src/backend/kms/device.rs
src/backend/kms/surface/mod.rs
src/input/mod.rs
src/wayland/handlers/screencopy/mod.rs
src/wayland/handlers/screencopy/render.rs
src/wayland/handlers/screencopy/user_data.rs
src/wayland/protocols/screencopy.rs

This seems to fix https://github.com/pop-os/cosmic-comp/issues/1305. xdg-desktop-portal-cosmic prints an error, buy retries (as it should for an `Unknown` error; though maybe there should be a retry limit) and the session continues working.
Not sure if it should be sending `failed`, or queuing it with the next frame so it can send `success` to the client, but this works and is desirable as a failsafe anyway.

protocols/screencopy: Make frame/session send stopped/fail on drop

---

src/input/mod.rs

Previously, a click on a client like squeekboard would give keyboard focus to the window behind it, if any.
If we are in the input region of the layer surface, we shouldn't give keyboard focus to the surface behind it on click. And should just leave the focus unchanged. Returning `None` here seems to be correct.

Don't change focus on click of layer with `KeyboardInteractivity::None`

---

Cargo.lock
Cargo.toml
src/backend/kms/surface/mod.rs

Fixes an issue where a dual GPU system would keep allocating dGPU PBOs in `cpu_copy()` every frame, but `cleanup()` was not being called, since the surface thread for the builtin output was rendered on the primary/integrated GPU, targeting the same GPU.
Even if a different monitor was compositing on the dGPU, That wouldn't help since that thread has it's own `GpuManager` with it's own renderer and cache.
Running cleanup at the end (or start) of each frame seems like a good idea. Not sure if it would be best to avoid additional calls, or if that's desirable/fine.

kms/surface: Call `cleanup_texture_cache` for each device at end of draw

---

Cargo.lock
Cargo.toml
src/backend/kms/mod.rs

Previously, if `expected_node` couldn't import a buffer, it would print an error, then try the next node. There shouldn't really be a reason to attempt import if the format/modifier isn't in `dmabuf_texture_formats`.
It seems the issue I've been seeing with cosmic-workspaces crashing the Nvidia driver is fixed by removing this, and disabling `dma_shadow_copy` (which was producing the same error). Importing Nvidia buffers on the AMD GPU seems to be causing issues.
Not sure how `dma_shadow_copy` should be fixed, but a test for supported formats is easy to add here anyway.

kms: Do not attempt to import dmabuf on device not supporting format

---

src/debug.rs
src/input/mod.rs
src/shell/focus/mod.rs
src/shell/focus/target.rs
src/shell/mod.rs
src/wayland/handlers/xwayland_keyboard_grab.rs

A solution for https://github.com/Smithay/smithay/issues/1714.
With this, the lock screen is able to get keyboard focus normally, but focus then reverts to the XWayland grab surface. This can be tested with the example client from the issue.
Adding a new variant of `KeyboardFocusTarget` is annoying. Maybe it could map to a different variant of the enum. But it presumably needs to handle any `wl_surface` XWayland uses. (Override redirect surfaces? Subsurfaces?)

Improved handling of XWayland grabs

---

src/shell/grabs/moving.rs

Fixes #1253
~~As a bonus, now it snaps to edges across outputs. There might be issues if there are multiple outputs with edges very close to each other, as there is no priority measures in place to, for example, snap to the one closest or has a cursor on, but in practice nobody should have that kind of setup.~~

fix: Make window snapping apply properly on multiple-output configurations

---

Cargo.lock
Cargo.toml
src/dbus/logind.rs
src/dbus/mod.rs
src/input/mod.rs
src/shell/mod.rs
src/state.rs
src/utils/prelude.rs

Adds logic to inhibit systemd handling lid-switches for us, if more than one output is connected.
Handles lid-switches by disabling the built-in output on all systems. (Verified this doesn't break compiling/running/closing-the-lid without the systemd-feature.)
Fixes https://github.com/pop-os/cosmic-comp/issues/1351

feature: Handle lid-switch events

---

src/wayland/handlers/layer_shell.rs
src/wayland/handlers/xdg_shell/mod.rs

There are some additional panel and applet changes for grabs, but this should enable grabs for popups on layer shell surfaces.

fix: check layer map for root popup surface

---

src/backend/kms/device.rs
src/backend/kms/surface/mod.rs
src/backend/render/cursor.rs
src/backend/render/mod.rs
src/shell/element/mod.rs
src/shell/element/stack.rs
src/shell/element/surface.rs
src/shell/element/window.rs
src/shell/grabs/moving.rs
src/shell/layout/floating/mod.rs
src/shell/layout/tiling/mod.rs
src/shell/workspace.rs
src/wayland/handlers/compositor.rs

An attempt at smarter plane usage.
If we end up compositing on the gpu anyway, it rarely makes sense to use hardware compositing as well, given the render time will be basically the same no matter if we composite 6 or 5 surfaces.
However if only a handful of elements are actually updating, we could potentially skip software composition all together if those would be placed on hardware planes. This ends up happening very rarely though, as from cosmic-comp's perspective the shell components are usually the first in the render-order, making them hug the hardware composition chain.
To fix this, lets introduce some filtering for viable scanout targets. We expect targets with a rather constant or high refresh rate to be good candidates as frequent updates would frequently require re-rendering …

Filter overlay plane candidates

---

src/backend/kms/device.rs
src/backend/kms/mod.rs
src/config/mod.rs
src/dbus/logind.rs
src/dbus/mod.rs
src/input/mod.rs
src/state.rs

This should improve our handling of disabled outputs and fix https://github.com/pop-os/cosmic-comp/issues/1562 in the process.
- 6cfbb7a - Previously we always re-enumerated disabled connectors on `device_changed`, which added them back to the `OutputConfigurationState`, even if they remained disabled and wrote the config to disk.
- c9c3503 - Previously we reloaded outputs for every single event. This was especially problematic after standby, when call `device_changed` for every single device. Potentially calling read_outputs before we have evaluated a device, which lost an output, causing modesetting errors on `apply_config_for_outputs` in the kms-backend.
- eec7279 - Resets configs that disable every output
- 5fcde81 - Previously our inhibitor/lid-state could break, if we missed a …

Improvements around disabled outputs

---

data/tiling-exceptions.ron

Will be used by https://github.com/pop-os/cosmic-store/pull/229

Float cosmic-store dialogs, needed for gstreamer codec install

---

Cargo.lock
Cargo.toml
src/backend/kms/device.rs
src/backend/kms/surface/mod.rs
src/backend/render/mod.rs
src/backend/winit.rs
src/backend/x11.rs
src/wayland/handlers/screencopy/render.rs

Uses https://github.com/Smithay/smithay/pull/1805 to get a sync point from the blit, and then waits on it in a calloop source without blocking the thread.
Like https://github.com/pop-os/cosmic-comp/pull/1580, this should fix some screen capture synchronization issues, but without the overhead of a `glFinish`.

kms/surface: Don't send screencopy`success()` until sync point is reached

---

cosmic-comp-config/src/workspace.rs
src/shell/mod.rs
src/shell/workspace.rs
src/wayland/handlers/workspace.rs
src/wayland/protocols/workspace/ext.rs
src/wayland/protocols/workspace/mod.rs

The `id` is defined to be sent only once, on creation of the handle or later. And only for workspaces that are "likely to be stable across multiple sessions".
Set we add an `id` initially for pinned workspaces, and add one when the workspace is pinned.
The `id` is not supposed to be human readable, so we just use a random value.
I don't think we currently have any plans that would need this feature, but this will allow scripts to recognize that a pinned workspace is the same as a workspace from a previous session, and do things like move a certain application to that workspace.
We'll need to update clients with https://github.com/pop-os/cosmic-protocols/pull/62 before merging this.

protocols/workspace: Set ext workspace `id` for pinned workspace

---

cosmic-comp-config/src/input.rs
cosmic-comp-config/src/lib.rs
src/config/mod.rs

Touchpad toggle functionality for https://github.com/pop-os/cosmic-comp/issues/732 via cosmic-config.
@ids1024 This needs obviously a new system-action as well, but otherwise is this enough for cosmic-osd?

config: Allow overriding touchpad state

---

Cargo.lock
Cargo.toml
src/backend/kms/device.rs
src/backend/kms/mod.rs
src/backend/kms/render/gles.rs
src/backend/kms/render/pixman.rs
src/backend/kms/surface/mod.rs

Fixes https://github.com/pop-os/cosmic-comp/issues/144
Turns out the stupidest solution is the fastest...
The biggest changes are in smithay to fix llvmpipe (https://github.com/Smithay/smithay/pull/1811), but a few additional commits here clean up support for display link and other software devices. In general we don't want to expose hardware acceleration related features:
- Never consider a software based gpu a primary node (we have fallbacks for when no primary node is set)
- Don't advertise dmabuf-support for software gpus
- Don't advertise their outputs for leasing
- Don't test dmabuf imports on them
- Work around cursor bugs on evdi specifcially
I have another commit that uses what mutter describes as "zero-copy" (https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/810) or how …

Software rendering support

---

src/backend/render/mod.rs
src/shell/layout/tiling/mod.rs

Latest smithay update allows us to fix a potential `PixelShaderElement` leak. (Which mostly concerns some very small uniforms, but still.)

render: Fix shader obj leak

---

src/backend/kms/device.rs
src/backend/kms/mod.rs
src/backend/kms/surface/mod.rs

This partially reverts https://github.com/pop-os/cosmic-comp/pull/1624/commits/91af833e286ea645e95cb2f7865fe94ab9c5d5c8 to not join threads on `apply_config_for_output` disabled and thus dropped surfaces.
This is hopefully a temporary fix until a better solution is found upstream (e.g. https://github.com/Smithay/smithay/pull/1820), since this prevents us from immediately re-using any freed crtcs.
Fixes https://github.com/pop-os/cosmic-comp/issues/1631
Closes https://github.com/pop-os/cosmic-epoch/issues/2133

kms: Don't join on `DrmSurface` drop

---

src/wayland/handlers/screencopy/render.rs

It seems https://github.com/pop-os/cosmic-comp/pull/1638 caused an issue in cosmic-workspaces, where if there are multiple toplevels, when dragging a toplevel, the drag surface would appear in capture for other toplevels.
For now, omit drag surface in toplevel capture without `draw_cursor`. Though I guess ultimately we do want it for metadata cursor capture in the portal, but not in cosmic-workspaces? Maybe the protocol needs some additional option for this...

screencopy: Without `draw_cursor`, omit dnd icon from toplevel capture

---

src/shell/focus/target.rs

Tested on `SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=1 supertux2`, using XWayland. If the game starts with fullscreen configured, it minimizes immediately on start. But after this change, this no longer happens.
This hopefully will improve behaviors with various X11/wine fullscreen clients. It may fix https://github.com/pop-os/cosmic-comp/issues/1510, though looking at the video the behavior there may be a bit different.

focus: Check if X11 surface matches in `KeyboardFocus::replace()`
