src/shell/grabs.rs
This has been annoying me.
Moving tiling windows between monitors seems to work nicely with this change. Floating windows are positioned incorrectly when moved to another monitor, but this is existing behavior.
=> Fix position window is rendered during drag with multiple outputs

src/input/mod.rs
Fixes https://github.com/pop-os/cosmic-comp/issues/36
@ids1024 Is this roughly, what you had in mind?
Instead of silently discarding the returned error, cosmic-comp tries to recover by loading a standard config now and afterwards crashes explicitly, instead of some time later due to a missing `KeyboardHandle`.
=> input: Don't ignore keyboard init failures

src/backend/kms/mod.rs
It seems this is all that's needed to make cosmic-comp run in a VM without graphics acceleration.
Fixes https://github.com/pop-os/cosmic-comp/issues/62.
=> kms: Use primary node if no render node is found

src/state.rs
This seems to fix https://github.com/pop-os/cosmic-comp/issues/58. Though in the future the default behavior in Smithay may need some improvement.
=> Update primary scanout output when not visible on previous output

src/input/mod.rs, src/shell/element/mod.rs, src/shell/element/stack.rs, src/shell/element/window.rs, src/shell/focus/mod.rs, src/shell/mod.rs
=> Fix latest window not getting focus when switching from a "fullscreen" workspace

debian/control
=> Add cmake to debian/control Build-Depends to fix package compilation

Makefile, debian/rules, debian/source/options, src/input/mod.rs
Commits were lost from the history after merge
=> fix zombie processes

Cargo.toml
Includes output transform fix: https://github.com/Smithay/smithay/pull/1039.
=> Update smithay to latest commit

.github/workflows/build.yml, flake.lock, flake.nix
Things done:
- migrate from flake-utils to flake-parts for easier composability
- use rust-overlay from oxalica since it works well with rust-toolchain.toml files
=> nix: fix builds and CI

Cargo.lock, Cargo.toml, src/backend/render/element.rs, src/backend/render/mod.rs, src/debug.rs, src/input/mod.rs, src/shell/element/mod.rs, src/state.rs
Depends on https://github.com/Smithay/smithay-egui/pull/11.
=> Update `smithay-egui` and fix compilation of `debug`

Cargo.lock, Cargo.toml, src/state.rs, src/wayland/handlers/mod.rs, src/wayland/handlers/xwayland_keyboard_grab.rs
Cosmic-comp implementation for https://github.com/Smithay/smithay/pull/1093.
=> Xwayland keyboard grab

Cargo.lock, Cargo.toml, src/backend/kms/mod.rs, src/backend/winit.rs, src/backend/x11.rs, src/input/mod.rs, src/shell/element/mod.rs, src/shell/element/stack.rs, src/shell/element/surface.rs, src/shell/element/window.rs, src/shell/focus/target.rs, src/shell/grabs/mod.rs, src/shell/grabs/moving.rs, src/shell/layout/floating/grabs/resize.rs, src/shell/layout/tiling/grabs/resize.rs, src/shell/mod.rs, src/state.rs, src/utils/iced.rs, src/wayland/handlers/mod.rs, src/wayland/handlers/pointer_gestures.rs, src/wayland/handlers/security_context.rs
The boilerplate to add pointer gestures is a bit verbose, but not that complicated. And it works, for instance for pinch zooming in Firefox.
For building with the `debug` feature to work, https://github.com/Smithay/smithay-egui/pull/12 will be needed.
=> Update smithay, add pointer gestures and security context

flake.nix
=> fix: add cosmic-comp-config to nix flake

config.ron
Super+m should toggle maximize by default
=> Add maximize shortcut

src/shell/layout/floating/mod.rs
This PR fixes a bug where a floating window resizes after being moved
fixes: #179
=> Fixes floating window resizing after being moved

src/backend/kms/mod.rs, src/wayland/handlers/drm_lease.rs, src/wayland/handlers/mod.rs
Little side-project to SteamVR stuff working on Cosmic. ~~Not terribly well tested yet.~~ Seems to work fine with SteamVR at least.
=> wayland/kms: Add drm_lease implementation

src/backend/kms/mod.rs
=> kms: don't fail when encountering render-only devices

src/shell/element/stack/tabs.rs
Fixes lagging tab animations by discarding the expired animations when adding new animations, or doing a cleanup of animations.
=> fix(shell): lagging tab animations

flake.lock, flake.nix, src/backend/winit.rs, src/backend/x11.rs
- include build inputs into the dev shell to be able to `cargo {cmd}` inside
- pin all deps to a single `nixpkgs` version
- small error handling improvements (needed those errors while debugging)
=> nix: setup dev shell

src/wayland/handlers/xdg_activation.rs
This seems to fix an issue where the workspace for the activated settings wasn't appearing as urgent when spawning another instance of settings by the launcher from another workspace. Is this not intended?
=> fix: set the workspace of the activated token's surface to urgent if not focusing it

src/backend/render/mod.rs, src/input/mod.rs, src/session.rs, src/shell/element/mod.rs, src/shell/element/stack.rs, src/shell/element/surface.rs, src/shell/layout/floating/grabs/resize.rs, src/shell/layout/floating/mod.rs, src/shell/layout/tiling/grabs/swap.rs, src/shell/layout/tiling/mod.rs, src/shell/mod.rs, src/shell/workspace.rs, src/state.rs, src/systemd.rs, src/wayland/handlers/screencopy.rs, src/wayland/handlers/selection.rs, src/wayland/handlers/xdg_shell/mod.rs, src/xwayland.rs
~~Needs more testing~~
Fixes #232.
Fixes #230.
=> More Xwayland fixes

src/xwayland.rs
=> xwayland: Consider fullscreen requests for unmapped windows

src/shell/grabs/moving.rs
~~Still needs to be tested outside of windowed mode.~~ works now
Fixes #240
=> moving: Fix dragging against lower/right screen edges

src/main.rs, src/session.rs
I've tested this with cosmic-greeter and some other cosmic apps and it appears to work. It always exits with the exit status of the command, or with `1` if the command is killed with a signal.
=> Implement kiosk mode for cosmic-greeter

Cargo.lock, cosmic-comp-config/src/workspace.rs, src/input/mod.rs, src/shell/mod.rs, src/shell/workspace.rs, src/wayland/handlers/workspace.rs, src/wayland/protocols/workspace.rs
=> Workspace protocol updates

cosmic-comp-config/src/lib.rs, src/backend/render/mod.rs, src/config/mod.rs, src/input/mod.rs, src/shell/mod.rs
Can be tested with https://github.com/pop-os/cosmic-applets/pull/214
=> feat: add tiling variables to cosmic config

src/backend/render/cursor.rs, src/shell/element/stack.rs, src/shell/element/surface.rs, src/shell/element/window.rs, src/shell/layout/tiling/mod.rs, src/shell/mod.rs, src/shell/workspace.rs
Fixes https://github.com/pop-os/cosmic-comp/issues/261
=> Interactive resize zone for server-side decorated windows and stacks.

src/shell/grabs/moving.rs, src/shell/layout/floating/mod.rs
=> floating window mouse tiling updates

src/input/mod.rs
This appears to work, but the implementation seems way to easy. Draft PR while I am running it a bit more to test for any regressions.
Fixes #384
=> input: Move window anywhere with Super-key

Cargo.lock, Cargo.toml, src/input/mod.rs, src/main.rs, src/utils/mod.rs, src/utils/rlimit.rs
~~Draft as this still needs testing, but~~ Seems to work well, this should increase our client limit and avoid crashing from buggy clients (though ddos-ing the server with large amounts of file descriptors is still possible).
=> main: Increase soft file limit

config.ron
Requires https://github.com/pop-os/cosmic-greeter/pull/27
=> Use loginctl lock-session instead of running cosmic-greeter

src/backend/render/mod.rs
Fixes https://github.com/pop-os/cosmic-workspaces-epoch/issues/25.
=> Exclude DnD surfaces from workspace capture

src/wayland/protocols/screencopy.rs
Before this, `/proc/$(pidof cosmic-comp)/maps` quickly expands in length when cosmic-workspaces is opened and closed a bunch of time, preventing the GPU memory from being freed. Which on my Intel system can lead to OOM eventually.
There may be other leaks to deal with, but `maps` no longer shows this issue.
=> screencopy: Fix reference cycle, that leaks buffer

src/wayland/protocols/screencopy.rs
Cosmic-workspaces was having an issue when the compositor sent `ready`, `failed`, then `stopped`. This could be worked around client-side, but presumably the compositor should never send more than one `failed`/`ready` for a particular frame.
It seems cleaner to have `FrameInner::fail` as the only place that sends `failed`. So any checks can be there. I believe the logic there should be appropriate for every call.
=> screencopy: Don't send `fail` after `ready`

src/input/mod.rs, src/shell/mod.rs, src/state.rs, src/wayland/handlers/idle_inhibit.rs, src/wayland/handlers/idle_notify.rs, src/wayland/handlers/mod.rs
Initial support for idle notify and idle inhibit.
=> Support for idle notify and idle inhibit

src/input/mod.rs
We need to call `add_tablet` for each tablet device, not just if the capability is new. Also, the tool needs to be added with `add_tool`.
`xournalpp` seems to be working now.
=> Fix tablet input

config.ron
Requires https://github.com/pop-os/cosmic-launcher/pull/131
=> feat: add alt-tab shortcut

cosmic-comp-config/src/lib.rs, src/config/mod.rs, src/shell/seats.rs
Hi !
This PR updates the `xkb_config` file structure and handling to allow for setting the keyboard repeat rate and delay.
Thanks !
=> feat: configurable keyboard repeat rate and delay

Cargo.lock
Includes https://github.com/pop-os/libcosmic/pull/482, and fixes https://github.com/pop-os/cosmic-comp/issues/530.
=> Update libcosmic to fix assertion error

Cargo.lock, Cargo.toml, src/state.rs, src/wayland/handlers/alpha_modifier.rs, src/wayland/handlers/mod.rs
Requires https://github.com/Smithay/smithay/pull/1448.
=> Add `alpha-modifier-v1` protocol

Cargo.lock, Cargo.toml, src/backend/render/element.rs, src/input/mod.rs, src/shell/element/mod.rs, src/shell/element/stack.rs, src/shell/element/window.rs, src/shell/grabs/menu/mod.rs, src/shell/grabs/mod.rs, src/shell/grabs/moving.rs, src/shell/layout/floating/grabs/resize.rs, src/shell/layout/floating/mod.rs, src/shell/layout/tiling/grabs/resize.rs, src/shell/layout/tiling/mod.rs, src/shell/mod.rs, src/shell/workspace.rs, src/wayland/handlers/compositor.rs
Changing pointer/touch events to use `f64` is annoying, but not too complicated.
=> Update to latest Smithay version

Cargo.lock, src/shell/element/stack/tab_text.rs, src/shell/element/window.rs
should fix #333 
This updates libcosmic to https://github.com/pop-os/libcosmic/commit/8e67f3ce1c0e953c444a2ec43e70a78abcf17400.
Text has a new field wrap.
=> feat: double click to maximzie

.github/workflows/build.yml, src/backend/kms/surface/mod.rs, src/shell/element/mod.rs
Having a CI test should make it easy to catch this sort of thing.
Lets see if CI passes here...
=> Fix build with `debug` and `profile-with-tracy`; add CI test

Cargo.lock, data/keybindings.ron
This needs https://github.com/pop-os/cosmic-settings-daemon/pull/41
=> Add PlayPause controls

src/backend/kms/device.rs
This makes it so 200% is used on displays with some axis greater than 1600 pixels and zero size.
=> Use fallback scale if size is invalid

src/shell/mod.rs
- Issue #760: Fully resolved.
- Issue #725: Partially resolved:
- Touchpad Gesture Navigation: The issue is fixed for the first workspace, but it still persists in the last workspace.
- Keyboard Navigation: Fully resolved across all workspaces.
The changes might lead to unexpected animation behaviour elsewhere, because I probably have not tested everything.
=> Fixing Animation bugs when switching workspaces

src/input/mod.rs
resolves #754 
4-finger gestures should now follow user setting for natural scroll on touchpad
=> Natural 4-finger gestures

flake.lock, flake.nix
=> Update and fix flake.nix

Cargo.lock, Cargo.toml, src/backend/kms/surface/mod.rs, src/backend/render/mod.rs, src/debug.rs, src/shell/element/mod.rs, src/wayland/handlers/pointer_constraints.rs
Requires https://github.com/Smithay/smithay/pull/1195 and https://github.com/Smithay/smithay-egui/pull/16.
=> Update `egui`, `smithay-egui`

src/backend/kms/surface/mod.rs, src/state.rs, src/utils/env.rs, src/utils/mod.rs
Like `anvil`. Useful for testing and working around issues.
=> Add `COSMIC_DISABLE_DIRECT_SCANOUT` env var

src/shell/layout/floating/grabs/resize.rs
similar to the `MoveGrab` <sup>[1]</sup> <sup>[2]</sup>, this sets the `CursorIcon` shape in `ResizeSurfaceGrab::new` and unsets it in the `Drop` impl.
the match over `ResizeEdge` may not be exhaustive, but currently these are the only values being passed into the function.
[1]: https://github.com/pop-os/cosmic-comp/blob/9a9eddb132a308bd4de17a143e1e4919bfc9c7b1/src/shell/grabs/moving.rs#L715-L718
[2]: https://github.com/pop-os/cosmic-comp/blob/9a9eddb132a308bd4de17a143e1e4919bfc9c7b1/src/shell/grabs/moving.rs#L855-L858
=> set cursor shape for resize grabs

src/wayland/protocols/toplevel_info.rs
=> toplevel_info: Fix racy data creation

src/input/mod.rs
Depends on https://github.com/Smithay/smithay/pull/1593.
=> Apply output transform to touch/tablet events

Cargo.lock, data/keybindings.ron
should be merged just after https://github.com/pop-os/cosmic-settings-daemon/pull/58
=> Alt shift tab

src/utils/iced.rs
fixes #1050 scaling for SSD and stacks.
=> fix(iced): use internal_ref size

src/shell/mod.rs
Fixes https://github.com/pop-os/cosmic-comp/issues/1008
=> shell: Fix stacking maximized windows

Cargo.lock, Cargo.toml
Depends on https://github.com/Smithay/smithay/pull/1635.
Hopefully helps with debugging https://github.com/pop-os/cosmic-comp/issues/1124
=> Better drm logs

Cargo.lock, Cargo.toml, src/backend/render/mod.rs
Requires https://github.com/Smithay/smithay-egui/pull/19.
=> Update `smithay-egui`, `egui`

src/backend/kms/mod.rs
If any issues with the syncobj protocol come up, or any issues we suspect may be related to it, an env var may be helpful.
=> Add a `COSMIC_DISABLE_SYNCOBJ` env var to disable syncobj protocol

src/wayland/protocols/workspace.rs
https://github.com/pop-os/cosmic-comp/pull/668 previously did this for toplevel events, but missed the fact that the workspaces protocol has the same issue.
Fixes https://github.com/pop-os/cosmic-workspaces-epoch/issues/61.
=> workspace: Fix race between binding `wl_output` and `output_enter`

Cargo.lock, Cargo.toml, src/backend/render/cursor.rs, src/backend/render/mod.rs, src/config/mod.rs, src/shell/layout/floating/mod.rs, src/shell/layout/tiling/mod.rs
Also pulls in some general fixes from https://github.com/pop-os/cosmic-comp/pull/1173
=> chore: Update smithay

src/shell/grabs/moving.rs
https://github.com/pop-os/cosmic-comp/pull/1189#issuecomment-2659006687
=> Make edge snapping variable names more consistent-er

Cargo.lock, data/keybindings.ron
Applies https://github.com/pop-os/cosmic-settings-daemon/pull/71
=> feat: add shortcut for input source switch

resources/i18n/nl/cosmic_comp.ftl
Makes Dutch translation for the zoomed view consistent with Cosmic-Settings
=> i18n(nl) update Dutch translation

src/shell/layout/tiling/mod.rs, src/shell/workspace.rs
Fixes https://github.com/pop-os/cosmic-epoch/issues/1640
Fixes https://github.com/pop-os/cosmic-comp/issues/1258
=> tiling: Exclude maximized windows from input/render

src/input/mod.rs
=> input: Fix events for subsurfaces of lock surface

Cargo.lock, Cargo.toml, src/backend/kms/render/gles.rs, src/backend/kms/surface/mod.rs, src/backend/render/cursor.rs, src/backend/render/element.rs, src/backend/render/mod.rs, src/backend/winit.rs, src/backend/x11.rs, src/debug.rs, src/shell/element/mod.rs, src/shell/element/stack.rs, src/shell/element/surface.rs, src/shell/element/window.rs, src/shell/grabs/menu/mod.rs, src/shell/grabs/moving.rs, src/shell/layout/floating/mod.rs, src/shell/layout/tiling/mod.rs, src/shell/workspace.rs, src/shell/zoom.rs, src/utils/iced.rs, src/utils/screenshot.rs, src/wayland/handlers/screencopy/render.rs
Draft until https://github.com/Smithay/smithay/pull/1669 is merged.
Fixes https://github.com/pop-os/cosmic-comp/issues/1287
Also fixes zoom crash and other weird threaded interactions with the iced-integration.
=> iced: Don't throttle resizes

Cargo.lock, Cargo.toml, src/backend/kms/device.rs, src/backend/kms/mod.rs, src/backend/kms/surface/mod.rs, src/backend/render/element.rs, src/backend/render/mod.rs, src/backend/render/shaders/offscreen.frag, src/backend/winit.rs, src/backend/x11.rs, src/config/mod.rs, src/shell/element/mod.rs, src/state.rs, src/wayland/handlers/a11y.rs, src/wayland/handlers/output_configuration.rs, src/wayland/handlers/screencopy/render.rs, src/wayland/protocols/a11y.rs
Supersedes https://github.com/pop-os/cosmic-comp/pull/1058
Requires:
TODO:
=> a11y: screen filters

Cargo.lock, Cargo.toml, cosmic-comp-config/src/lib.rs, src/config/mod.rs, src/input/mod.rs, src/shell/focus/mod.rs, src/shell/focus/target.rs, src/xwayland.rs
.. and a couple of xwayland related fixes
~~Blocked on https://github.com/Smithay/smithay/pull/1694~~
=> Allow Xwayland to eavesdrop on certain key/mouse events to allow global shortcuts

src/shell/element/window.rs
Fixes https://github.com/pop-os/cosmic-comp/issues/690
=> shell/element: Attach a resize border to tiled undecorated windows

src/backend/kms/surface/mod.rs
If `redraw()` returned early, before updating `self.state`, but after calling `queue_frame`, `on_vblank` would later be called, and reach `unreachable` since state isn't set to `WaitinfForVBlank`.
In particular, this was happening when the dmabuf from the image copy frame failed to `bind`.
To avoid this, make sure to update `self.state` immediately after calling `queue_frame`, before any early return from an error.
This fixes a crash I see with Intel+Nvidia screen capture and https://github.com/pop-os/xdg-desktop-portal-cosmic/pull/76. I need to try another fix to see if I can get capture to actually work.
=> kms/surface: Fix thread crash on error return of `redraw`

.github/workflows/build.yml, Cargo.lock, Cargo.toml, rust-toolchain.toml, src/input/actions.rs, src/shell/element/window.rs, src/state.rs, src/wayland/protocols/workspace/mod.rs
`libcosmic` has a `rust-version` of 1.85, so update toolchain to that, and update libcosmic and other dependencies.
=> Update Rust version, and dependencies

src/backend/kms/surface/mod.rs
This follows up https://github.com/pop-os/cosmic-comp/pull/1408 by making sure errors in screencopy don't result in `redraw()` exiting early with an error, which is easiest done by splitting that part of the function off into a different function. It also splits off a couple more functions from `redraw`.
This is still a bit ugly, but it seems nice to structure things a bit more, and not keep growing `redraw()` with more functionality. (It would help if `take_screencopy_frames()` could work without mutating `elements`...)
=> kms/surface: Split off a couple parts of `redraw()` into different functions, and change how screencopy errors are handled

Cargo.lock, src/config/mod.rs, src/input/mod.rs
requires:
https://github.com/pop-os/cosmic-settings-daemon/pull/85
https://github.com/pop-os/cosmic-osd/pull/110
=> feat: power button handling

src/wayland/handlers/toplevel_management.rs, src/wayland/handlers/xdg_shell/mod.rs, src/xwayland.rs
Fixes #1520 and #1522.
@ids1024 can you test that it works with the wayland backend on the itch.io variant as well?
=> shell: Don't unconditionally focus on unfullscreen

src/shell/element/stack.rs
should fix https://github.com/pop-os/cosmic-applets/issues/449
=> fix: only activate the active window of the stack on activation

src/backend/kms/surface/mod.rs
Should fix https://github.com/pop-os/cosmic-comp/issues/1472
=> kms: Correctly handle the source node not being initialized

src/wayland/handlers/xdg_activation.rs
This should resolve https://github.com/pop-os/cosmic-applets/issues/855
=> Activation token

src/backend/kms/device.rs
This should fix https://github.com/pop-os/cosmic-comp/issues/1592 by making sure we don't accidentally re-configure outputs, that already existed, but were disabled previously.
Ping @jacobgkau
=> kms/device: Don't reconfigure existing outputs on `connector_added`

src/shell/mod.rs
=> fix: don't assume previous workspace still exists #1588

data/keybindings.ron
Fixes https://github.com/pop-os/cosmic-comp/issues/1625
=> chore: add Alt+F4 shortcut to close windows
